Add instructions how to update wallet.rs in the backend
iotaledger/firefly pull request #1253
Opened 2021-07-09 11:10 UTC by Thoralf-M

# Description of change

Add instructions how to update wallet.rs in the backend

## Type of change

- Docs (changes to the documentation)

2021-07-14 05:31 UTC, rajivshah3 requested changes

2021-07-14 05:31 UTC, rajivshah3 commented on packages/backend/README.md
> +After that write `yarn` in `firefly\packages\backend\bindings\node`.
```suggestion
To test another branch of wallet.rs you have to change the dependency in `firefly/packages/backend/Cargo.toml`.

Then, to test this change or just to update to the latest commit you need to run `cargo update` in `firefly/packages/backend` **and** in `firefly/packages/backend/bindings/node/native`.

After that, run `yarn` in `firefly/packages/backend/bindings/node`.
```

2021-07-15 12:30 UTC, laumair approved these changes

2021-07-15 12:46 UTC, rajivshah3 approved these changes

2021-07-19 22:04 UTC, merged