feat: Send fiat amount
iotaledger/firefly pull request #1431
Opened 2021-08-27 19:46 UTC by maxwellmattryan

# Description of change

- Adds user's chosen fiat currency to list of denominations in dropdown menu for when sending a transaction
- Adds more functions to core lib with tests: `convertFromFiat` and `isFiatCurrency`
- Adds a constant, `DUST_THRESHOLD`, indicating what is considered dust

## Links to any relevant issues

- #763
- #1168 

## Type of change

- New (a change which implements a new feature)

## How the change has been tested

__Both software and Ledger profiles__ have been tested with this change.

Tested on:

- MacOS (Catalina 10.15.7)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-22 11:16 UTC, nicole-obrien commented
@maxwellmattryan Just reviewing your PR:
When sending IOTA, if I enter the an amount in IOTA that is more than the supply then amount is truncated to the maximum supply. If I am entering a fiat amount and I send an amount that is really big then the application semi-freezes and when I delete the amount the subtext stays there and I am unable to navigate to anything else within the application.

2021-09-27 16:05 UTC, nicole-obrien requested changes
Added individual comments, but let's test this on ledger before approval.

2021-09-28 02:13 UTC, maxwellmattryan commented on packages/shared/routes/dashboard/wallet/views/Send.svelte
> +        let hasDustRemaining = Math.abs(from.balance - _amount) < 1_000_000
Have defined a constant `DUST_THRESHOLD` for in `currency.ts` ~

2021-09-28 02:19 UTC, maxwellmattryan commented on packages/shared/components/inputs/Amount.svelte
> +        console.log('AMT: ', _amount)
Yeah 😅

2021-09-28 02:19 UTC, maxwellmattryan commented on packages/shared/components/inputs/Amount.svelte
> +    type AmountUnit = Unit | string
Change has been made!

2021-09-28 02:20 UTC, maxwellmattryan commented
Thanks for reviewing, @nicole-obrien. I've made some changes and the PR is good to be merged given your approval!

2021-09-28 08:06 UTC, nicole-obrien reviewed
Did you test the changes on desktop and ledger?

2021-09-28 13:29 UTC, maxwellmattryan commented
@nicole-obrien 

> Did you test the changes on desktop and ledger?

Yep, they're good to go!

2021-09-28 15:29 UTC, nicole-obrien approved these changes

2021-09-28 17:56 UTC, merged