Feat: Kickoff mobile support
iotaledger/firefly pull request #1592
Opened 2021-10-08 18:21 UTC by begonaalvarezd

# Description of change

This PR aims to kickoff mobile support. 

TODO:
- [x] Adjust Webpack for mobile, update Capacitor to v3.0 and add support for Capacitor live reload.
- [x] Kickoff dashboard and child components for mobile, excluding graphs.
- [x] Kickoff onboarding views and child components for mobile (except migration)
- [x] Abstract electron and capacitor to platform API
- [x] Connect iOS bindings
- [ ] Connect Android bindings
- [ ] Capacitor Pincode Manager
- [ ] Capacitor Deeplink Manager
- [ ] Capacitor Notification Manager
- [ ] ...

Note: this is a WIP and the development so far is focused on the UI

## Links to any relevant issues

N/A

## Type of change

- New (a change which implements a new feature)
- Update (a change which updates existing functionality)

## How the change has been tested

In package/mobile run: 
```bash
# in packages/mobile
yarn
yarn build
yarn dev
```
To enable capacitor live reload, keep development server running, then in a new terminal run:
```bash
cp capacitor-sample.config.ts capacitor.config.ts 
# modify the url field "XXX.XXX.XXX.XXX" with your local IP
# update project files and open native IDE
yarn android:update
yarn ios:update
```

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that my latest changes pass CI tests
- [ ] New and existing unit tests pass locally with my changes

2021-10-13 12:58 UTC, nicole-obrien commented on packages/shared/components/Sidebar.svelte
> +{#if $mobile}
To be looked at in the future: https://github.com/iotaledger/firefly/discussions/1601

2021-10-13 14:07 UTC, begonaalvarezd commented on packages/shared/routes/setup/import/views/FileImport.svelte
> +    const onDrop = (buffer?, name?, path?) => {
`onFile` is also used on the `on:change` of the mobile input and the `on:click` of the button, if we name it backwards perhaps is also confusing. I'll rename this a bit, let me know if its still confusing

2022-02-01 12:50 UTC, nicole-obrien commented
This PR now aims to move mobile develop into the develop branch, so that these two branches don't end up a hard fork with complexities merging.

Tasks are now tracked under the initial https://github.com/iotaledger/firefly/milestone/2

2022-02-01 13:16 UTC, nicole-obrien approved these changes
Let's get this merged, before I have to sort anymore merge conflicts!

2022-02-01 13:29 UTC, nicole-obrien requested changes
Unable to scroll down on settings page

2022-02-02 01:14 UTC, nicole-obrien approved these changes
Merging before I have to retest this branch. All mobile dev should now be targeting develop.

2022-02-02 19:01 UTC, merged