Feat: Mobile Pincode manager
iotaledger/firefly pull request #1712
Opened 2021-12-10 23:05 UTC by amadeu2

# Description of change

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking (any change that would cause existing functionality to not work as expected)
- New (a change which implements a new feature)
- Update (a change which updates existing functionality)
- Fix (a change which fixes an issue)
- Docs (changes to the documentation)
- Chore (refactoring, build scripts or anything else that isn't user-facing)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that my latest changes pass CI tests
- [ ] New and existing unit tests pass locally with my changes

2022-01-12 22:02 UTC, nicole-obrien requested changes
How come we are making a making a function that returns an object of three functions and assigning the result of calling that function to a variable, instead of the original skeleton which was an object with three functions?

2022-01-18 23:50 UTC, amadeu2 commented
> How come we are making a making a function that returns an object of three functions and assigning the result of calling that function to a variable, instead of the original skeleton which was an object with three functions?

I tend to use this pattern with Svelte for state encapsulation but here is no sense, like you said it's better to use just an object literal to simplify. Just fixed that, thanks.

2022-01-19 21:37 UTC, nicole-obrien commented on packages/mobile/capacitor/lib/pincodeManager.ts
> +     * @method get
Should we keep the original comment?

2022-01-19 21:43 UTC, amadeu2 commented on packages/mobile/capacitor/lib/pincodeManager.ts
> +     * @method get
fixed, thanks!

2022-01-19 21:45 UTC, nicole-obrien approved these changes
LGTM 👩‍🎤

2022-01-19 21:46 UTC, merged