Feat: Account customization UI
iotaledger/firefly pull request #1774
Opened 2021-12-17 14:54 UTC by jeeanribeiro

# Description of change

Adds accounts colors and pattern customization 

## Type of change

- Enhancement (a non-breaking change that adds functionality)

## How the change has been tested

- Create wallet
- Edit existing account and change color and pattern
- Create a new account and choose color and pattern
- Close the app and login again
- Hover AccountTiles (the chosen color and pattern should show)
- Edit account (color and patterns saved should be selected)
- Use mouse hover and click or keyboard tab and enter to select colors and patterns options

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-11 16:06 UTC, begonaalvarezd commented on packages/shared/locales/pt-BR.json
> +        },
we should undo all the changes in this file, the CI and the community in crowdin will take care of the translation 🙏🏼

2022-01-26 14:44 UTC, nicole-obrien requested changes
Currently if you are customising an existing wallet, you can only click save if the name has changed, even if you change colour or pattern.

Wallet switcher colours seem to break. Although this will be changed in the future, it is worth quickly fixing this too.

2022-01-27 12:09 UTC, nicole-obrien requested changes
There are still some issues:

1. The graphs are no longer using the custom colour in this branch, here is what it looks like in 1.3.3 followed by this branch.

<img width="378" alt="Screenshot 2022-01-27 at 12 06 03" src="https://user-images.githubusercontent.com/89913787/151355646-582b81c5-2741-4f17-93e7-0f9f2810b70f.png">
<img width="429" alt="Screenshot 2022-01-27 at 12 08 28" src="https://user-images.githubusercontent.com/89913787/151356016-e0120410-c9d4-4956-a101-7f16b827f08f.png">

2. The colours are still not random when a profile is restored through backup, mnemonic or when accounts are found in balance finder. This is present in 1.3.3.

2022-02-01 11:57 UTC, nicole-obrien approved these changes
Approved with some suggestions for the future. 😄

2022-02-01 11:57 UTC, nicole-obrien commented on packages/shared/components/AccountTile.svelte
> +    $: textColor = isBright(color) ? 'gray-800' : 'white'
`isBright(color) ? 'gray-800' : 'white'`
This piece of code is used in a lot of files so potentially could be abstracted out.

2022-02-01 11:57 UTC, nicole-obrien commented on packages/shared/components/ColorPicker.svelte
> +<script lang="typescript">
Super confusing file, with the various states the styles can be in. Would be good to clean this up in the future and maybe separate the custom picker as its own component.

2022-02-01 11:57 UTC, nicole-obrien commented on packages/shared/lib/helpers.ts
>          }, {})
We can do this in the major refactor coming, but we should have separate helper files for different topics under a helper folder, i.e. this is related to colours.

2022-02-01 11:57 UTC, nicole-obrien commented on packages/shared/lib/profile.ts
> +export interface ProfileAccount {
Should separate interfaces into type files. Will be covered by the big refactor.

2022-02-01 11:57 UTC, merged