feat: transaction search and filtering
iotaledger/firefly pull request #1857
Opened 2021-12-22 23:27 UTC by jeeanribeiro

# Description of change

Adds transaction counter, search (transaction addresses and balance), and filtering (all, incoming, outgoing)
https://github.com/iotaledger/firefly/discussions/655

## Type of change

- New (a change which implements a new feature)

## How the change has been tested

- Have some transaction history in the account
- Access account history screen
- Test filters (all, incoming and outgoing)
- Test search by balance or transaction addresses
- Test search + filter

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that my latest changes pass CI tests
- [x] New and existing unit tests pass locally with my changes

2022-01-11 09:34 UTC, begonaalvarezd commented on packages/shared/components/icon/icons.js
> +                d: 'M11.1922 12.6064C10.0236 13.4816 8.57236 14 7 14C3.13401 14 0 10.866 0 7C0 3.13401 3.13401 0 7 0C10.866 0 14 3.13401 14 7C14 8.57232 13.4816 10.0236 12.6064 11.1921L16.0001 14.585
Im going to update the path of this icon to follow the rules of the other icons in the UI Kit

2022-01-11 09:35 UTC, begonaalvarezd commented on packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
> +                                {filter}
if we use `{filter}` we cant translate it. Better localize it

2022-01-11 09:41 UTC, begonaalvarezd commented on packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
> +            filteredTransactions = transactions.filter(transaction => transaction.payload.data.essence.data.incoming)
to avoid possible crashes might be good using `transaction?.payload?.data?.essence?.data?.incoming` everywhere

2022-01-11 12:20 UTC, begonaalvarezd commented on packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
> +                                {filter}
Updated

2022-01-11 12:23 UTC, begonaalvarezd commented on packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
> +                receiverAddressesFromTransactionPayload(transaction?.payload).find(addr => addr.includes(searchValue))
What about adding here also a match for `messageID`?

2022-01-17 09:39 UTC, begonaalvarezd commented on packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
> +            return transaction?.id?.includes(searchValue)
This will only search the messageID if the transaction is not of type `Transaction`

2022-01-17 09:56 UTC, begonaalvarezd commented on packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
> +    $: if (searchValue) {
perhaps we could add a `debounce`?

2022-01-17 09:57 UTC, begonaalvarezd commented on packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
> +                    <Input bind:value={searchValue} classes="z-0" style="padding: 0.75rem  2.5rem;" />
I would also add a focus when the search opens

2022-01-26 15:13 UTC, nicole-obrien requested changes
Currently crashes after the following steps:
- Click wallet
- Click search icon
- Click on any transaction to view details

This is the error in the console:
<img width="443" alt="Screenshot 2022-01-26 at 15 13 03" src="https://user-images.githubusercontent.com/89913787/151190222-549abe8c-fff7-42ca-9c3e-d4d69258d20e.png">

2022-01-27 11:40 UTC, nicole-obrien requested changes
Two more points from me:
- When filtering and then clicking the search bar the current filter is not displayed, but transactions displayed are only the filtered ones. This might be confusing to the user. Maybe we can revisit this at a later time.
- When searching by value it is only checking the raw iota value, but we display to the user a simplified balance e.g. 1343902990 would be 1.30 Gi. Therefore I think the user should also receive results for the balance that is displayed in the transaction history view. so searching for 1.3 would show that result or even searching Gi would show that result to.

2022-01-28 05:40 UTC, jeeanribeiro commented
> Two more points from me:
> 
> * When filtering and then clicking the search bar the current filter is not displayed, but transactions displayed are only the filtered ones. This might be confusing to the user. Maybe we can revisit this at a later time.
> * When searching by value it is only checking the raw iota value, but we display to the user a simplified balance e.g. 1343902990 would be 1.30 Gi. Therefore I think the user should also receive results for the balance that is displayed in the transaction history view. so searching for 1.3 would show that result or even searching Gi would show that result to.

Latest changes:
When the search is active the filter is reset.
I've changed the search function to [trinity search algorithm](https://github.com/iotaledger/trinity-wallet/blob/c6d8e798ad503b8592a4e0c1b2955dc253c0e9da/src/shared/libs/iota/transfers.js#L1111)

2022-01-28 17:25 UTC, nicole-obrien requested changes
New changes don't seem to be working properly, I would revert back to the previous search function and add condition like this: 
`formatUnitBestMatch(transaction?.payload?.data?.essence?.data?.value).toString()?.includes(searchValue)`

2022-02-01 00:57 UTC, nicole-obrien approved these changes
LGTM, thanks for all the changes as requested 🙏

2022-02-01 01:00 UTC, merged

2022-03-24 15:17 UTC, JannemanDev commented
I dont know if intentional but search on address only matches when there is a full match not if found as substring.
For example when I have a tx in my history from this address: `atoi1qptd4dlt2870zsa9fn5t98mnt2zsstlert0wd20uesk0h4thzavmgrld8kk`
and I search on `atoi1qptd4dlt2870zsa9fn5t98mnt2zsstlert0wd20uesk0h4thzavmgrld8` (I removed last two chars) it will not show up.
Tested with FireFly 1.4 Alpha 1.

Personally I think it can be handy to search on substring... when you look at an address you only have to remember a few chars (instead of having to copy and paste which takes more time *and* sometimes isn't even possible when its on a different device) most of the time to be able to find it in history.

2022-03-24 15:20 UTC, nicole-obrien commented
> I dont know if intentional @nicole-obrien  but search on address only matches when there is a full match not if found as substring.
> 
> For example when I have a tx in my history from this address: `atoi1qptd4dlt2870zsa9fn5t98mnt2zsstlert0wd20uesk0h4thzavmgrld8kk`
> 
> and I search on `atoi1qptd4dlt2870zsa9fn5t98mnt2zsstlert0wd20uesk0h4thzavmgrld8` (I removed last two chars) it will not show up.
> 
> Tested with FireFly 1.4 Alpha 1.
> 
> 
> 
> Personally I think it can be handy to search on substring... when you look at an address you only have to remember a few chars (instead of having to copy and paste which takes more time *and* sometimes isn't even possible when its on a different device) most of the time to be able to find it in history.

That's a valid point, I can see if this is a quick fix.