chore: polish voting
iotaledger/firefly pull request #2563
Opened 2022-03-16 22:25 UTC by jeeanribeiro

## Summary
- Dark/light theme fixes
- Responsive layout fixes
- Not found treasury event state layout and working buttons
- Voting button's layout fixes
- i18n to strings in governance event details
- Removes wallet pill
- Makes "Learn about voting with Firefly" link to work (added on Electron URL whitelist)

## Relevant Issues
closes #2299

## Type of Change
Please select any type below that applies to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [x] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

## Testing
### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Test everything in governance flow with attention to details

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-03-17 11:42 UTC, Tuditi requested changes
I left some comments, but great work in general. UI is starting to look really good!

2022-03-17 11:42 UTC, Tuditi commented on packages/shared/routes/dashboard/governance/views/GovernanceInfo.svelte
> +        <Text type="p" classes="truncate">{localize('views.governance.info.link')}</Text>
Same problem as with other button. Text should be centered.

2022-03-23 02:36 UTC, jeeanribeiro commented on packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
> +        <Button secondary onClick={handleViewNodeSettingsClick} classes="border-transparent">
I agree, I've pinged them in Discord, would be better if we change the text to be in the center

2022-03-24 02:56 UTC, jeeanribeiro commented on packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
> +        <Button secondary onClick={handleViewNodeSettingsClick} classes="border-transparent">
But we could do it as enhancement and not block this task

2022-03-24 08:58 UTC, Tuditi commented on packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
> +        <Button secondary onClick={handleViewNodeSettingsClick} classes="border-transparent">
Very true, I created an issue for it.

2022-03-24 08:58 UTC, merged