[wip] feat: adds voting tx locale/icon
iotaledger/firefly pull request #2620
Opened 2022-03-24 02:43 UTC by jeeanribeiro

## Summary
Adds logic for showing participation events tx icon and locale

## Relevant Issues
closes #2445 

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [x] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

## Testing
### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-04-14 19:02 UTC, Tuditi requested changes
Getting in shape, there are some minor thing that need to be changed. I also have some issues with icons if the ID's are wrong. This has to be tackled with a stored array of past event ID's or an even better solution.

2022-04-14 19:02 UTC, Tuditi commented on packages/shared/components/ActivityRow.svelte
> +    $: {
Maybe this should be a function?

2022-04-15 10:10 UTC, begonaalvarezd commented on packages/shared/components/ActivityRow.svelte
> +                initialsColor = getColor($activeProfile, acc.id) as string
This line has been removed in `develop` anyway, now activity row doesnt depend on wallet color anymore

2022-04-17 20:03 UTC, jeeanribeiro commented on packages/shared/lib/participation/participation.ts
> +        const messageMilestone = 0
Sorry, I've not added any comments and also forgot about it.
The idea is to have the latest milestone before the treasury event commencing state, so by default if a participate tx is before that milestone it should show as staking.
So we don't have this milestone yet, I will include a TODO comment

2022-04-19 12:29 UTC, Tuditi approved these changes
LGTM!

2022-04-21 11:20 UTC, merged