Fix/disallow account switching
iotaledger/firefly pull request #2703
Opened 2022-03-31 13:44 UTC by Tuditi

## Summary

Switching account while voting/staking/transferring/syncing leads to UI inconsistencies.
This is tackled in this PR. The account switcher modal doesn't open and a popup tells 
the user that they need to wait until the corresponding action is finished.

### Changelog
```
Account Switching modal only when no UI inconsistencies could be present
If modal doesn't open, notifications are shown
```

## Relevant Issues

closes: https://github.com/iotaledger/firefly/issues/2688

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

## Testing
### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [ ] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-03-31 19:53 UTC, maxwellmattryan commented
The code LGTM and it works in the app. It's good to be merged after resolving the one comment I left :slightly_smiling_face:

2022-03-31 22:50 UTC, jeeanribeiro commented on packages/shared/locales/en.json
> +        "syncing": "Wait until synchronization is finished to change account!",
I agree with your comments, I also think that we could remove the exclamation mark to have soft communication with the user

2022-03-31 23:23 UTC, jeeanribeiro requested changes
All working, I would just change the messages to be softer

2022-04-01 07:27 UTC, Tuditi commented on packages/shared/locales/en.json
> +        "syncing": "Wait until synchronization is finished to change account!",
The strict guy in me has spoken again. I'll change it :D

2022-04-01 13:45 UTC, jeeanribeiro approved these changes
:rocket:

2022-04-01 14:14 UTC, merged