enhancement: change airdrop tile for multiple periods
iotaledger/firefly pull request #2768
Opened 2022-04-06 20:49 UTC by maxwellmattryan

## Summary
The `StakingAirdrop` components needs to accommodate for multiple staking periods.

### Changelog
```
TODO
```

## Relevant Issues
- Closes #2759

## Type of Change
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [x] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

## Testing
### Platforms
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-04-06 23:40 UTC, nicole-obrien requested changes
Getting this error sending a transaction
![](https://cdn.discordapp.com/attachments/958382308983996526/961407136674488370/Screenshot_2022-04-07_at_00.28.38.png)

2022-04-07 08:44 UTC, begonaalvarezd commented on packages/shared/components/popups/Transaction.svelte
> -    import { selectedAccountParticipationOverview, stakingEventState } from 'shared/lib/participation/stores'
`stakingEventState` can not be removed because its used in line 51

2022-04-07 16:21 UTC, nicole-obrien requested changes
Nearly there, just a few comments 🌆

2022-04-07 23:05 UTC, nicole-obrien approved these changes
🚀 🚀 🚀

2022-04-07 23:05 UTC, merged