refactor: export backup with stardust api
iotaledger/firefly pull request #3430
Opened 2022-06-10 12:47 UTC by nicole-obrien

## Summary
This refactors the backup logic to use the new stardust api, and refactors the logic into its own action. As well as changing the style of the backup popup used when backing up from the warning in the profile menu.

### Changelog
```
- Restyle backup popup
- Change app logic to use new api
- Move app logic out of components
```

## Relevant Issues
Please list any related issues (e.g. bug, task).

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [x] __Update__ - a change which updates existing functionality

## Testing
### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [x] MacOS
	- [ ] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-06-11 09:23 UTC, Tuditi requested changes
I can export the backup, but not import it again. Should we tackle that here? There is also a bug in the import router, I'll open an issue for it, since it's unrelated to your PR.

Otherwise if exported from settings, the notification is shown next to the button and not as a regular notification

2022-06-11 09:29 UTC, nicole-obrien commented
@Tuditi There are issues open with respect to importing on the M2 milestone. If it doesn't work we need to pick those up as separate PRs

2022-06-12 19:23 UTC, nicole-obrien commented on packages/shared/components/popups/Index.svelte
> +        backupStronghold: BackupStrongholdPopup,
huh? I have been slowly renaming the popup components to include the word popup in them so you know its a popup. But the left hand side doesn't need the word popup as this is just the type of popup when calling the open popup function.

2022-06-12 19:33 UTC, nicole-obrien commented
@Tuditi 
> Otherwise if exported from settings, the notification is shown next to the button and not as a regular notification

That was expected behaviour

2022-06-12 19:35 UTC, nicole-obrien commented on packages/shared/components/Button.svelte
> +    export let iconWidth: string = undefined
For some reason I was getting error somewhere saying that I didn't input a value for these props. And I don't know why. Reverted and not getting the error.

2022-06-13 07:04 UTC, Tuditi commented on packages/shared/components/popups/Index.svelte
> +        backupStronghold: BackupStrongholdPopup,
Aah okay, I was talking about the right hand side, since all the other components don't have the word Popup in them.

2022-06-13 10:32 UTC, merged