chore: update onboarding mobile
iotaledger/firefly pull request #3503
Opened 2022-06-14 02:19 UTC by amadeu2

## Summary
Update onboarding for mobile.

### Changelog
```
Closes #3216 
Closes #3217 
Closes #3218 
```

## Relevant Issues
Please list any related issues (e.g. bug, task).

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [ ] __Update__ - a change which updates existing functionality

## Testing
### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [ ] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-06-14 15:42 UTC, paul-boegelsack approved these changes

2022-06-20 07:51 UTC, paul-boegelsack requested changes
We have to be more careful with the merge conflicts. It seems that there are changes in the PR which overwrite previously implemented features.

2022-06-20 07:51 UTC, paul-boegelsack commented on packages/mobile/capacitor/capacitorApi.ts
> -import { ActionSheet, ShowActionsOptions } from '@capacitor/action-sheet'
Same as in electronApi

2022-06-20 07:51 UTC, paul-boegelsack commented on packages/mobile/package.json
> -        "@capacitor/action-sheet": "^1.0.8",
Same as in electronApi.

2022-06-20 07:51 UTC, paul-boegelsack commented on packages/shared/lib/tests/mocks/platform.ts
> -import { ActionSheetOptions } from '../../typings/actionSheet'
Shouldn't be deleted I guess.

2022-06-20 07:51 UTC, paul-boegelsack commented on packages/shared/lib/tests/mocks/platform.ts
> -    },
Shouldn't be deleted I guess.

2022-06-20 07:51 UTC, paul-boegelsack commented on packages/shared/lib/typings/actionSheet.ts
> -}
Shouldn't be deleted.

2022-06-20 07:51 UTC, paul-boegelsack commented on packages/shared/lib/typings/platform.ts
> -    showActionSheet(options: ActionSheetOptions): Promise<number>
Shouldn't be deleted.

2022-06-20 15:17 UTC, closed without merging

2022-06-20 15:18 UTC, amadeu2 commented
I made a new branch cherry picking only needed changes