ui: adjust animations
iotaledger/firefly pull request #3515
Opened 2022-06-15 01:25 UTC by kraftjs

## Summary
Please summarize your changes, describing __what__ they are and __why__ they were made.
This branch is based on #3514.

Update animations in onboarding routes according to Figma design and added animations to OnboardingProtocol and OnboardingNetwork files.

### Changelog
```
- Added animations to OnboardingNetwork.svelte and OnboardingProtocol.svelte
- Changed Setup.svelte animation to match Figma
- Deleted Secure.svelte animation and moved it to Profile.svelte (Secure.svelte is joining RecoveryPhrase.svelte)
- Moved previous Profile.svelte animation to OnboardingNetwork.svelte
- Moved previous import-success animation to OnboardingProtocol.svelte
```
#### Todo
- Previous import-success animation will be replaced with matching Figma animation once I get the JSON file

## Relevant Issues
Please list any related issues (e.g. bug, task).
Closes #3513 

## Type of Change
Please select any type below that is applicable to your changes, and delete those that are not.
- [ ] __Breaking__ - any change that would cause existing functionality to not work as expected
- [ ] __Chore__ - refactoring, build scripts or anything else that isn't user-facing
- [ ] __Docs__ - changes to the documentation
- [ ] __Fix__ - a change which fixes an issue
- [ ] __New__ - a change which implements a new feature
- [x] __Update__ - a change which updates existing functionality

## Testing
### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [ ] Linux
	- [x] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-06-17 18:22 UTC, jeeanribeiro requested changes
conflicts with the base branch

2022-06-20 11:20 UTC, begonaalvarezd commented
Thoughts:
- Some animations added in this PR are quite "chrysalis branded" (the diamond). We should discuss if we want to keep them. 
- We probably shouldnt add any animation that is not in figma, first we should get figma updated with the final animations

Follow discussion in discord `firefly-design`

2022-07-08 21:40 UTC, jeeanribeiro requested changes
The protocol/network animations looks larger than the others, I think that they should be smaller

![image](https://user-images.githubusercontent.com/42754063/178073846-3de3766e-d19e-497d-9876-cea07e8b8421.png)

![image](https://user-images.githubusercontent.com/42754063/178073864-3441dfff-b1d7-4df4-8aa2-7d1eb1a20220.png)

2022-07-12 16:15 UTC, jeeanribeiro approved these changes

2022-07-12 16:22 UTC, merged