fix: adjusted padding of account navigation
iotaledger/firefly pull request #3737
Opened 2022-06-29 09:30 UTC by paul-boegelsack

## Summary

Deleted the x padding of the selection because it moved the selection too far to the left.

## Changelog

```
- Deleted x padding of the account selection
```

## Relevant Issues

Closes #3674

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [X] iOS
  - [X] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-06-29 13:04 UTC, begonaalvarezd reviewed
IMO, the issue with the wrong alignment comes from the translate X calculation, not the paddings. 
I see couple of things we need to fix around this:
- Make sure the account top navigation is horizontally aligned.
- When you change the name of the account (and increase its name by a lot) the element stays in the previous position, this needs a new calculation

2022-06-30 08:03 UTC, amadeu2 requested changes
I've just tested and happens what Begoña says. Do you think it's doable to achieve?

2022-06-30 08:53 UTC, paul-boegelsack commented
> IMO, the issue with the wrong alignment comes from the translate X calculation, not the paddings.

Your right, my fix attempt with the padding was brainless 😅 The calculation worked with the center of the button not with the center of the text.

> I've just tested and happens what Begoña says. Do you think it's doable to achieve?

 I tried 😄 Now the selection is aligned with its text and not with the button center itself. When the text resizes through a wallet name update it should recenter the selection again.

2022-07-01 16:05 UTC, begonaalvarezd commented on packages/shared/components/AccountNavigation.svelte
> +        fix/center-the-account-selection
🕵🏼 this looks like a wrong merge

2022-07-01 16:19 UTC, paul-boegelsack commented on packages/shared/components/AccountNavigation.svelte
> +        fix/center-the-account-selection
😱 Thanks, you saved me.

2022-07-01 16:27 UTC, merged