fix: problems with account action titles for delete and hide an account
iotaledger/firefly pull request #3994
Opened 2022-07-25 09:43 UTC by paul-boegelsack

## Summary

This PR fixes the bug that causes the app to freeze when the hide action is selected. 
Additionally, it centers the title of the deleted wallet action

## Changelog

```
- Added class attribute to hide wallet title and added necessary tailwind classes
- Centered delete wallet action title
```

## Relevant Issues

Closes #3939

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [x] iOS
  - [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-07-26 23:08 UTC, amadeu2 requested changes
I can't reproduce it 😅 where is the fix for the app crash? I can see only the css center code. 
I think I discovered another issue here. To match desktop behavior, when we create a new wallet, the other wallet should allow to be hidded and currently it shows the delete option rather than the hide option. I think it's about to the latest changes on desktop with merges and we should pair it with components at `drawerContent` folder. We could have a call to discuss it well tomorrow

2022-07-27 08:12 UTC, paul-boegelsack commented
> I can't reproduce it 😅 where is the fix for the app crash? I can see only the css center code. 

The fix is actually the css center code 😅 The tailwind classes were added to the type attribute not the classes attribute. That causes the crash, when the component has loaded. 

>  I think I discovered another issue here. To match desktop behavior, when we create a new wallet, the other wallet should allow to be hidded and currently it shows the delete option rather than the hide option.

Yeah, I discovered the same while fixing the crash: 

https://github.com/iotaledger/firefly/issues/3998

> We could have a call to discuss it well tomorrow

Sounds good, just schedule when it fits for you 👍

2022-07-27 11:55 UTC, amadeu2 commented
> The fix is actually the css center code sweat_smile The tailwind classes were added to the type attribute not the classes attribute. That causes the crash, when the component has loaded.

Ahh 😄 perfect then I'll test that right now!
 
> > I think I discovered another issue here. To match desktop behavior, when we create a new wallet, the other wallet should allow to be hidded and currently it shows the delete option rather than the hide option.
> 
> I discovered the same while fixing the crash and was wondering as well:
> 
> #3998

Awesome just added it to TODO colomn, so let's merge it asap

> > We could have a call to discuss it well tomorrow
> 
> Sounds good, just schedule when it fits for you +1

maybe we could talk about it tomorrow better, thanks!

2022-07-27 11:58 UTC, amadeu2 approved these changes

2022-07-27 11:59 UTC, merged