enhancement: add error handling during login
iotaledger/firefly pull request #4320
Opened 2022-08-23 22:52 UTC by nicole-obrien

## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

...

## Changelog

```
- Please write a list of changes
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-08-25 09:39 UTC, MarkNerdi requested changes
In general it's a nice way to handle error

But the namings are only adapted to Clienterrors, even though we would do the same things for non-`ClientErrors` thrown by wallet.rs. It wouldn't really make sense to create different Enums and Regexs for different `error.type`s. 

Therefore I think we can remove the layer `ErrorFromApi`, because what interests us essentially is only the error message we get.

So 
CLIENT_ERROR_REGEX -> ERROR_REGEX 
ClientError -> (Api?)Error

wdyt?

2022-08-25 09:39 UTC, MarkNerdi commented on packages/shared/lib/core/error/constants/api-error-parameters.constant.ts
> +    { [key in ErrorFromApi]?: { [key in ClientError]?: Partial<IErrorParameters> } }
i think this type isn't correct.
If the toplevel key is `ErrorFromApi.ClientError` then the subkeys can be of type `ClientError`.
But if the toplevel key is e.g. `ErrorFromApi.InsufficientFundsError`  (which you get from walletrs as `{type: "InsufficientFunds", message: "insufficient amount of funds ..."}`, we wouldn't add these subtypes in the `ClientError` enum

2022-08-25 09:39 UTC, MarkNerdi commented on packages/shared/lib/core/error/utils/handleClientError.ts
> +export function handleClientError(error: IError): void {
i would generalize this. i think we would do the exact same for not only errors with `type: ClientError` right?

2022-08-25 09:46 UTC, nicole-obrien commented
@MarkNerdi there are a whole load of error types that can be thrown by wallet.rs. Some of them we will just have a catch all error for some we want to check the error message to see if it's a specific error we want to handle in a certain way. Because the switch statements for the regexes would potentially evaluate them all I think it's more efficient and sensible to only do the regexes for the types and messages we want. Rather than creating one linear list. Hence it's probably more efficient to filter on the type first. That's also because the fall back handling for each error type might be different. We might want to show error notification for client errors but not another type etc

2022-09-01 08:11 UTC, MarkNerdi approved these changes

2022-09-01 08:32 UTC, merged