fix: filter polishing
iotaledger/firefly pull request #4489
Opened 2022-09-06 13:46 UTC by jeeanribeiro

## Summary
All filter polishing related tasks to Stardust included here

## Relevant Issues
- [x] closes #4234
- [x] closes #4300
- [x] closes #4448
- [x] closes #4449
- [x] closes #4450
- [x] closes #4451
- [x] closes #4452

## Testing

### Platforms
- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-09-07 15:08 UTC, MarkNerdi reviewed
Works perfect :tada:  
left on question

2022-09-07 15:08 UTC, MarkNerdi reviewed
Works perfect :tada:  
left on question

2022-09-07 15:15 UTC, jeeanribeiro commented on packages/shared/components/modals/FilterModal.svelte
> -        <div class="pb-1">
Maybe because of this div border, it was squared and did not show the rounded edge underneath it

2022-09-07 15:26 UTC, jeeanribeiro commented on packages/shared/components/inputs/Dropdown.svelte
> +    export let disableTyping = false
I agree with it :+1:

2022-09-07 21:00 UTC, nicole-obrien requested changes
<img width="1392" alt="Screenshot 2022-09-07 at 21 58 51" src="https://user-images.githubusercontent.com/89913787/188978116-8f6cd505-2ba6-4238-9779-7bc27b8fd03f.png">

- We are now cutting off the dropdowns that would otherwise overflow the menu.
- Additionally filtering by amount seems to crash FF

2022-09-08 07:35 UTC, MarkNerdi commented
For me filtering for amount works

2022-09-08 12:01 UTC, nicole-obrien approved these changes

2022-09-08 12:05 UTC, merged