enhancement: handle large token supplies and metadata
iotaledger/firefly pull request #4544
Opened 2022-09-13 14:56 UTC by MarkNerdi

## Summary
The protocol allows arbitrary large supplies and decimals for native tokens. If we have such a big value in an asset or activity, a lot of arithmetic bugs occur. 
So the least effort is to just hide those  

## Changelog

```
- hide assets in `AssetDropdown` and `AssetList` if decimals or balance is larger than intmax
- hide activities for the above hidden assets 
```

## Relevant Issues
Closes #4104 

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-09-14 07:18 UTC, Tuditi requested changes
Code wise one minor thing. I'm not happy with the fact that we have these limitations. Did we consider using the big.js library?

2022-09-14 07:18 UTC, Tuditi commented on packages/shared/lib/core/wallet/utils/isValidIRC30.ts
> +    return hasValidDecimals && hasValidTotal && hasValidAvailable
This is a limitation of JS, not of IRC30, so the name is incorrect. Possibly we should look into how to handle larger values by using BigInt or Big library in Javascript. Firefly should be able to handle these values.

2022-09-16 14:09 UTC, nicole-obrien requested changes
This doesn't cover the filters that we have in the activities

2022-09-20 08:35 UTC, Tuditi requested changes
Codewise it looks good! As discussed in our call, there are still two things that should be addressed:
1) Let's limit the they can input to 24
2) I experienced a bug when setting the activity filter first to `less than 1` and then updating it to `greater than 1`. Let me know if you need the stronghold backup of my profile to reproduce!

2022-09-21 11:51 UTC, Tuditi approved these changes
LTGM! :fire:

2022-09-21 11:54 UTC, merged