enhancement: nsis script
iotaledger/firefly pull request #4762
Opened 2022-09-29 12:57 UTC by jeeanribeiro

## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

...

## Changelog

```
- Please write a list of changes
```

## Relevant Issues
- [ ] #4529
- [ ] #4530
- [ ] #4531 

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-09-29 14:28 UTC, MarkNerdi requested changes
Please rmove the .dll fils for inetc

2022-09-29 14:28 UTC, Tuditi requested changes
One thing that needs adding I think

2022-09-29 14:28 UTC, Tuditi commented on packages/desktop/electron-builder-config.js
> +        debugLogging: true,
I think this is not enough. You also need to add the following line to installer.nsh:

`LogSet on`

2022-10-11 16:03 UTC, Tuditi approved these changes
LGTM! :fire:

2022-10-11 16:07 UTC, merged