feat: add custom asset sorting
iotaledger/firefly pull request #4789
Opened 2022-10-03 09:19 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

...

## Changelog

```
- Please write a list of changes
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-10-03 10:52 UTC, MarkNerdi commented on packages/shared/lib/core/wallet/utils/sortAssets.ts
> +    return asset1.balance.total > asset2.balance.total ? (asc ? 1 : -1) : asc ? 0.1 : 1
we need to find a way to determine date

2022-10-06 12:43 UTC, nicole-obrien requested changes
Getting an error when logging out on this branch

2022-10-12 09:00 UTC, nicole-obrien requested changes
Balance is not changing in the asset list in this example I sent all the BTC balance

<img width="1273" alt="Screenshot 2022-10-12 at 10 59 38" src="https://user-images.githubusercontent.com/89913787/195299180-fa5aac57-9f42-454a-9f76-5853aac48d8b.png">

2022-10-12 09:54 UTC, nicole-obrien approved these changes
LGTM!

2022-10-12 09:57 UTC, merged