feat: add mnemonic import view for stardust mobile
iotaledger/firefly pull request #4851
Opened 2022-10-10 21:58 UTC by paul-boegelsack

## Summary

This PR adds the router component to restore a profile via mnemonics.

## Changelog

```
- Adds router components for mnemonic recovery
- Updates profile setup for recovery
- Enables mnemonic recovery feature for stardust dev net
```

## Relevant Issues

Closes #4818

## Testing

Until the mobile bindings are ready, the `dev-mode/mobile-stardust` branch has to be utilized for testing:

1 `git checkout dev-mode/mobile-stardust` 
2 `git merge feat-mobile/new-mnemonic-import-view`
3 `yarn (root directory)`
4 `yarn build (packages/desktop)`
5 `yarn start (packages/desktop)`

press `ctrl + c` to change the color theme
press `ctrl + k` to toggle the keyboard

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-10-11 09:51 UTC, begonaalvarezd requested changes
Looking amazing 🚀 just added 2 mini comments to cleanup a bit the code but this is almost ready to merge, great work 💪🏼

2022-10-11 09:51 UTC, begonaalvarezd commented on packages/mobile/routes/onboarding/views/profile-recovery/ProfileRecoveryRouter.svelte
> +    setContext<ProfileRecoveryRouter>('importRouter', $profileRecoveryRouter)
I dont think this context is used, looks like debris

2022-10-11 09:51 UTC, begonaalvarezd commented on packages/mobile/routes/onboarding/views/profile-recovery/ProfileRecoveryRouter.svelte
> +    $profileRecoveryRouter.resetRoute()
I personally prefer doing this inside onMount so its more clear when its being triggered

2022-10-12 08:01 UTC, paul-boegelsack commented
> Looking amazing 🚀 just added 2 mini comments to cleanup a bit the code but this is almost ready to merge, great work 💪🏼

Alright, thank you! 👍

2022-10-12 09:25 UTC, begonaalvarezd approved these changes
🔥 on fire!

2022-10-12 09:25 UTC, merged