feat: tabbed nft activity details
iotaledger/firefly pull request #5183
Opened 2022-11-10 00:28 UTC by jeeanribeiro

## Summary
> Please summarize your changes, describing __what__ they are and __why__ they were made.

## Changelog
```
- Please write a list of changes
```

## Relevant Issues
closes #5167 

## Testing
### Platforms
- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

## Checklist
- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-11-15 01:16 UTC, nicole-obrien requested changes
Missing info from activity popup:
- Address

Missing some details from the transaction tab:
- Transaction time
- Expiration time
- Claimed status
- Claimed time
- Gifted storage deposit

Missing some info from NFT tab:
- NFT address
- Immutable issuer

2022-11-15 10:14 UTC, MarkNerdi commented on packages/shared/components/popups/ActivityDetailsPopup.svelte
> +        <NftActivityDetails activity={{ ...details }} />
please use the same approach as with the `Alias`:
```suggestion
        <nft-details class="w-full h-full space-y-6 flex flex-auto flex-col flex-shrink-0">
            <NftActivityDetails {activity} />
            <ActivityInformation {activity} />
        </nft-details>
```

2022-11-15 10:15 UTC, MarkNerdi commented on packages/shared/components/popups/ActivityDetailsPopup.svelte
> +        <NftActivityDetails activity={{ ...details }} />
+ remove line 101 - 109

2022-11-15 10:19 UTC, MarkNerdi commented on packages/shared/components/molecules/NftActivityDetails.svelte
> +    <ActivityInformation {activity} />
this component should not include the tabs

2022-11-15 10:21 UTC, MarkNerdi commented on packages/shared/components/popups/send/SendConfirmationPopup.svelte
>          {/if}
add the tabs here

2022-11-15 10:23 UTC, MarkNerdi requested changes
i suggested some changes to correctly adapt my template for the tabs, but if you think your approach has advantages that mine doesnt, we can gladly start a discussion on that

2022-11-15 16:09 UTC, jeeanribeiro commented on packages/shared/components/popups/MintNftConfirmationPopup.svelte
> +        />
All tabs, storage deposit is also important here

2022-11-16 13:18 UTC, nicole-obrien approved these changes
LGTM!

2022-11-16 13:21 UTC, merged