enhancement: foundry tab
iotaledger/firefly pull request #5233
Opened 2022-11-17 08:44 UTC by MarkNerdi

## Summary

Add foundry information tab to ActivityDetails

## Changelog

```
- Add foundry information tab to ActivityDetails
```

## Relevant Issues

Closes #5189 

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-11-18 00:24 UTC, nicole-obrien requested changes
Because you can mint a foundry without it following irc30. We should have three tabs:

- Transaction
- Foundry
  - Alias owner
  - Total supply
  - Circulating supply
  - Melted supply
- Token Metadata
  - If follows IRC30 we parse as key values etc
  - else we just show a metadata block: ideally formatted

2022-11-18 08:02 UTC, MarkNerdi commented
Currently we don't yet support non-IRC30 tokens. But I'm gonna implement the 3rd tab with the assumption for now that every token is IRC30.

2022-11-21 17:24 UTC, nicole-obrien commented on packages/shared/locales/en.json
> -        "mintNativeToken": {
if you change this then every language needs to be re translated, unless you change the key in all language files

2022-11-22 08:39 UTC, nicole-obrien requested changes

2022-11-22 09:48 UTC, nicole-obrien approved these changes
LGTM!

2022-11-22 09:48 UTC, merged