Feat/decode sc metadata
iotaledger/firefly pull request #5274
Opened 2022-11-22 15:22 UTC by Tuditi

## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

...

## Changelog

```
- Please write a list of changes
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-11-24 12:02 UTC, MarkNerdi requested changes
1 question + 1 code change

2022-11-24 12:02 UTC, MarkNerdi commented on packages/shared/lib/core/layer-2/actions/parseLayer2MetadataForTransfer.ts
> +    const { baseTokenAmount, nativeTokens } = parseAllowance(readStream)
this throws an error if `parseAllowance(readStream)` returns undefined

2022-11-24 16:40 UTC, Tuditi commented on packages/shared/lib/core/layer-2/actions/parseLayer2MetadataForTransfer.ts
> +    const forceOpenAccount = smartContractParameters['c'] === FORCE_OPEN_ACCOUNT
They are kind of arbitrary, but not something that will be changed before the release. 
You can find a list for the parameter calls the accounts contract here: https://github.com/iotaledger/wasp/blob/gpa/packages/vm/core/accounts/interface.go#L62-L76

2022-11-25 07:38 UTC, MarkNerdi approved these changes
LGTM, gj!

2022-11-25 08:04 UTC, merged