chore: define mobile platform
iotaledger/firefly pull request #5499
Opened 2022-12-22 22:32 UTC by amadeu2

## Summary

See https://github.com/iotaledger/firefly/issues/5143

## Changelog

```
- Please write a list of changes
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

...

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-12-23 09:01 UTC, begonaalvarezd requested changes
Added 2 minor comments

2022-12-23 09:01 UTC, begonaalvarezd commented on packages/shared/lib/core/app/enums/platform-option.enum.ts
> +    iOS = 'ios',
```suggestion
    IOS = 'ios',
```
based on our coding conventions, all enums need to be pascal case

2023-03-09 17:10 UTC, amadeu2 commented on packages/shared/lib/core/app/classes/platform.class.ts
> +mobile.set(process.env.PLATFORM === 'mobile')
thanks, have choose the option 1

2023-03-14 10:04 UTC, begonaalvarezd approved these changes

2023-03-14 10:06 UTC, merged