fix: proposal remove logic and UI
iotaledger/firefly pull request #5502
Opened 2022-12-23 15:57 UTC by jeeanribeiro

## Summary
Fixes the proposal remove logic by not allowing the user to remove the proposal if is there any account voting for proposal.
Adds a tooltip to explain why the remove proposal button is disabled.

## Relevant Issues
closes #5435 

## Testing
### Platforms
- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2022-12-23 16:36 UTC, Tuditi requested changes
There are some issues:
- We query `getParticipationOverview` a lot and it takes a long time for wallet.rs to respond. We should cache the response somehow and pass it around instead of sending an API request all the time (this should go into a separate PR).
- Related to above, remove proposal can be sometimes selected even if another account is voting due to the fact that the async/await function is slow.
- If I voted, I never see the option to stop voting anymore.

I added some minor comments, but maybe it's better to merge this PR first, so there are no conflicts for `isVotingForProposal`. https://github.com/iotaledger/firefly/pull/5501

2022-12-23 16:36 UTC, Tuditi commented on packages/shared/components/modals/ProposalDetailsMenu.svelte
> +            isAnyAccountVotingForProposal = await isAnyAccountVotingForSelectedProposal()
This is not an async function

2022-12-23 16:36 UTC, Tuditi commented on packages/shared/components/modals/ProposalDetailsMenu.svelte
> +    let deleteMenuItem
```suggestion
    let deleteMenuItem: HTMLDivElement
```

2022-12-23 17:22 UTC, Tuditi requested changes
Let's revisit this once we have the current votes available in Firefly. I cannot get the stop voting button to show and I am able to remove the vote proposal from certain accounts while not from others.

Issue to be closed before this one: https://github.com/iotaledger/firefly/issues/5495

2022-12-31 14:31 UTC, closed without merging

2022-12-31 14:32 UTC, jeeanribeiro commented
Closed until we have current counted votes per profile/account