feat: show current vote
iotaledger/firefly pull request #5557
Opened 2023-01-11 16:10 UTC by Tuditi

## Summary

Show the current vote of a user.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
	- [ ] MacOS
	- [ ] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2023-01-11 21:08 UTC, maxwellmattryan requested changes
Looks pretty good, just left some minor comments.

2023-01-11 21:08 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/governance/views/DetailsView.svelte
> +        })
Might be worth putting this into its own `utils` function in the `governance` module.

2023-01-11 21:08 UTC, maxwellmattryan commented on packages/shared/components/ProposalQuestion.svelte
> +    $: showMargin = isOpened || ((votedAnswerValue || votedAnswerValue === 0) && !isOpened) // votedAnswerValue 0 corresponds to abstained vote
Might be worth making a constant e.g. `ABSTAIN_ANSWER_VALUE` so we can remove this comment and use it elsewhere as needed.

2023-01-11 21:08 UTC, maxwellmattryan commented on packages/shared/components/ProposalQuestion.svelte
>      function setPercentagesFromAccumulated(): void {
Accumulated what? Need just slightly more specificity in the function name / variables below

2023-01-11 21:15 UTC, maxwellmattryan commented
Some observations after testing:

- The current voted answer is shown, but the indicator icon is missing the pulse animation.
- It's a bit strange that I can select / de-select the current voted answer whenever the question is collapsed - in the collapsed state it shouldn't be possible to de-select the answer IMO. It looks slightly strange if I expand a question, select a different answer, collapse the question, resulting in the current voted answer looking different from the others.
- When clicking on a proposal to see its details, the loading of the questions itself takes a noticeably long amount of time plus another noticeably long amount of time to display the current votes.

Those are all relatively small details that will help improve UX, but as of now it is looking really good. Great job :clap:

2023-01-12 13:59 UTC, Tuditi commented
I disabled the possibility to click on an answer when the question is disabled. I added tasks for the other remarks you made :relaxed: .

2023-01-12 20:28 UTC, maxwellmattryan commented
Perhaps is out of the scope of this PR just slightly, but one last piece of feedback - if I want to re-vote, with a single changed answer, I have to manually re-select the answers for every question even if they're already selected. I should be able to just select a different answer for only one question and have the "Vote" button become enabled.

2023-01-12 20:32 UTC, maxwellmattryan approved these changes
LGTM :fire: 

I added remaining polish tasks in #5546

2023-01-12 20:32 UTC, merged