feat: automatic proposal querying
iotaledger/firefly pull request #5558
Opened 2023-01-11 22:27 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

Official proposals should be automatically registered to the user's Governance dashboard.

## Changelog

```
- Add registerProposalsFromPrimaryNode function called in login
- Cleanup imports in login file
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

Create new profiles connected to node with voting events. Log into the profile more than once.

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [x] I have made corresponding changes to the documentation

2023-02-09 18:59 UTC, maxwellmattryan commented
@Tuditi One change I think can be made is that we don't register a proposal if it has already ended, but some things worth noting:
- Some users may want to be able to see all proposals, even if they've ended, so that they can see the results of the vote
- Checking the status means adding an extra API call per proposal ID that we get. We could suggest for the node team to change this API endpoint so that it returns the entire event rather just the ID, which would be sensible since it's unlikely that there will be many many events on a node anyway (but who knows?)

My thoughts are that we should just keep it simple for now and register everything, then we can see based on beta testing how users feel about having every single event registered.

2023-02-10 15:39 UTC, nicole-obrien requested changes
Left some comments, I recently cleaned up all our api requests so its not taking as long to load so we should be able to pull in all events from our nodes at login. 

We could also register the events for a node when we add it.

I also need to double check but the questions where not showing on the proposal details page 🤷‍♀️

2023-02-10 15:39 UTC, nicole-obrien commented on packages/shared/lib/contexts/governance/utils/getVotingEventIds.ts
> +export function getVotingEventIds(): Promise<ParticipationEventId[]> {
```suggestion
export function getVotingParticipationEventIds(): Promise<ParticipationEventId[]> {
```

2023-02-10 15:39 UTC, nicole-obrien commented on packages/shared/lib/contexts/governance/utils/index.ts
> +export * from './getVotingEventIds'
```suggestion
export * from './getVotingParticipationEventIds'
```

2023-02-10 15:39 UTC, nicole-obrien commented on packages/shared/lib/contexts/governance/actions/registerProposalsFromPrimaryNode.ts
> +export async function registerProposalsFromPrimaryNode(): Promise<void> {
Can this be more generic by just passing in a node and then we can decide what nodes to use where we call this. i.e. we don't usually have a primary node

2023-02-10 15:39 UTC, nicole-obrien commented on packages/shared/lib/contexts/governance/actions/registerProposalsFromPrimaryNode.ts
> +    const primaryNode = clientOptions?.primaryNode ?? clientOptions?.nodes[0]
We should just pass in the nodes, and we can call this in a wrapper function for all the nodes the user has.

2023-02-10 15:40 UTC, nicole-obrien commented
> Checking the status means adding an extra API call per proposal ID that we get. We could suggest for the node team to change this API endpoint so that it returns the entire event rather just the ID, which would be sensible since it's unlikely that there will be many many events on a node anyway (but who knows?)

I have already changed this, we a don't need any api call check the status of an event it can be calculated by the current milestone.

2023-02-11 16:21 UTC, nicole-obrien commented on packages/shared/lib/contexts/governance/actions/registerProposalsFromPrimaryNode.ts
> +export async function registerProposalsFromPrimaryNode(): Promise<void> {
If we don't have a primary node we do not need to throw an error, just dont attempt to register any proposals for that node.

2023-02-13 13:54 UTC, Tuditi approved these changes
Looks good, I left a comment wrt Nicole's requested changes.
Additionally, we'll need a way to store removed event IDs, since removed official events get added back on login.

2023-02-13 13:54 UTC, Tuditi commented on packages/shared/lib/contexts/governance/actions/registerProposalsFromNode.ts
> +    }
This error is redundant if you follow Nicole's suggestion.

2023-02-13 14:21 UTC, Tuditi requested changes
Tests are failing

2023-02-13 17:17 UTC, maxwellmattryan commented
@Tuditi

2023-02-13 17:18 UTC, maxwellmattryan commented
@Tuditi,

> Additionally, we'll need a way to store removed event IDs, since removed official events get added back on login.

Agreed, but per the call we had today let's do this as a separate task so we can get a release out.

2023-02-13 17:29 UTC, nicole-obrien approved these changes
LGTM!

2023-02-13 17:50 UTC, merged