feat-mobile: add shimmer claiming
iotaledger/firefly pull request #5590
Opened 2023-01-16 09:10 UTC by paul-boegelsack

## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
	- [ ] MacOS
	- [ ] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

2023-01-17 13:06 UTC, begonaalvarezd requested changes
Im getting an error when I try to claim my rewards 
```
Error: Unable to initialize Shimmer claiming account
    at initialiseFirstShimmerClaimingAccount
```
line `throw new CannotInitialiseShimmerClaimingAccountError()`

2023-01-17 17:02 UTC, paul-boegelsack commented
@Tuditi "Stronghold reported a procedure error: engine: fatal engine error: vault `VaultId(TcAMhLekJE6GhvWh6qTYL-T2DKgaUKz7)` does not exist" is thrown at initialiseFirstShimmerClaimingAccount.ts line 35.

2023-01-18 13:39 UTC, paul-boegelsack commented
> Im getting an error when I try to claim my rewards
> 
> ```
> Error: Unable to initialize Shimmer claiming account
>     at initialiseFirstShimmerClaimingAccount
> ```
> 
> line `throw new CannotInitialiseShimmerClaimingAccountError()`

Should work now thanks to @Tuditi

2023-01-23 18:28 UTC, maxwellmattryan requested changes
Have one tiny requested change - looks great!

2023-01-23 18:50 UTC, maxwellmattryan commented
I'm getting this error when trying to claim in a scenario where I've got funds on account index 2, address index 5:
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at getAccountAssetsForSelectedAccount (getAccountAssetsForSelectedAccount.ts:16:1)
    at selected-account-assets.store.ts:42:1
    at sync (index.mjs:77:1)
    at index.mjs:95:1
    at Object.subscribe (index.mjs:48:1)
    at subscribe (index.mjs:55:1)
    at get_store_value (index.mjs:60:1)
    at getOutputOptions (getOutputOptions.ts:24:1)
    at claimShimmerRewardsForShimmerClaimingAccount (claimShimmerRewards.ts:67:1)
    at async claimShimmerRewardsForShimmerClaimingAccounts (claimShimmerRewards.ts:42:1)
```

2023-01-24 08:05 UTC, paul-boegelsack commented on packages/mobile/views/onboarding/views/profile-setup/views/index.js
>  export { default as SetupRecoveredView } from './SetupRecoveredView.svelte'
Thank you for the catch 👍

2023-01-24 08:28 UTC, paul-boegelsack commented
> I'm getting this error when trying to claim in a scenario where I've got funds on account index 2, address index 5:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'toString')
>     at getAccountAssetsForSelectedAccount (getAccountAssetsForSelectedAccount.ts:16:1)
>     at selected-account-assets.store.ts:42:1
>     at sync (index.mjs:77:1)
>     at index.mjs:95:1
>     at Object.subscribe (index.mjs:48:1)
>     at subscribe (index.mjs:55:1)
>     at get_store_value (index.mjs:60:1)
>     at getOutputOptions (getOutputOptions.ts:24:1)
>     at claimShimmerRewardsForShimmerClaimingAccount (claimShimmerRewards.ts:67:1)
>     at async claimShimmerRewardsForShimmerClaimingAccounts (claimShimmerRewards.ts:42:1)
> ```

I tried to reproduce but without success. I created this with your fund spreader:
![image](https://user-images.githubusercontent.com/6748220/214241249-1c463a02-95bc-4adb-96e3-8e879763004a.png)

But I was able to claim and the account was created successfully.

I tried to debugg this line: `at getAccountAssetsForSelectedAccount (getAccountAssetsForSelectedAccount.ts:16:1)` Does the error occur when it loads the dashboard? 

`getAssetFromPersistedAssets(COIN_TYPE[networkProtocol].toString())`

Maybe it's setting the wrong network protocol for some reason?

2023-01-26 16:03 UTC, begonaalvarezd requested changes
Looking great 💪🏼 
Just 2 comments:
- I would flip the buttons in this screen 
![image](https://user-images.githubusercontent.com/3624944/214885775-9999b332-1953-4cd0-ab5c-0debcf4f653a.png)
- "rerun" button doesnt respond, repro steps:
```
use the same seed in desktop & mobile, a seed that has unclaimed funds
get into the screen where your next step is just claiming, on both desktop and mobile
claim with desktop, so mobile cant claim anymore, though it knowns about the transaction
if will display an error because it cant claim twice the same funds
---- until here, all is good behavior
firefly mobile suggests "rerun", you press the button, nothing happens
```
![image](https://user-images.githubusercontent.com/3624944/214885985-4958cea3-4cc0-436b-a145-f1bbb2365b41.png)

2023-01-26 17:10 UTC, begonaalvarezd approved these changes
🚀

2023-01-26 17:15 UTC, maxwellmattryan approved these changes

2023-01-26 17:20 UTC, merged