feat-mobile: balance breakdown
iotaledger/firefly pull request #5689
Opened 2023-01-27 17:37 UTC by begonaalvarezd

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

Depends on https://github.com/iotaledger/firefly/pull/5688, nested PR

## Changelog

```
- feat-mobile: balance breakdown
```

## Relevant Issues

Close https://github.com/iotaledger/firefly/issues/4967

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-01-30 13:01 UTC, paul-boegelsack requested changes
lgtm 🔥 I just added a comment because of the popup logic

2023-01-30 13:01 UTC, paul-boegelsack commented on packages/mobile/views/dashboard/drawers/account-actions/views/BalanceBreakdownView.svelte
> +        openPopup({
Reminder to remove the popup logic

2023-01-31 15:36 UTC, begonaalvarezd commented on packages/mobile/views/dashboard/drawers/account-actions/views/BalanceBreakdownView.svelte
> +        openPopup({
@paul-boegelsack fixed 🙏🏼

2023-02-01 09:10 UTC, paul-boegelsack approved these changes
🔥

2023-02-01 09:10 UTC, merged