chore: upgrade Electron to `23.1.0`
iotaledger/firefly pull request #5899
Opened 2023-02-16 15:31 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

To help with the Snyk CI failures, we need to update Electron to at least `22.2.0`.

## Changelog

```
- Increment Electron version to 23.1.0
- Update yarn.lock file
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

Test general app functionality.

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-02-17 10:54 UTC, Tuditi approved these changes
Works well, but merging this means we won't support windows 7/8/8.1.

2023-02-17 14:05 UTC, Tuditi requested changes

2023-02-17 14:05 UTC, Tuditi commented on packages/desktop/package.json
> +        "electron": "23.1.0",
Let's upgrade it to the latest 22 version, because otherwise we'll have windows support issues.

2023-02-20 10:46 UTC, Tuditi requested changes
There has been a newer electron release with a security fix.

2023-02-20 10:46 UTC, Tuditi commented on packages/desktop/package.json
> +        "electron": "22.2.1",
```suggestion
        "electron": "22.3.0",
```

2023-02-23 17:26 UTC, nicole-obrien approved these changes
Works on Mac

2023-02-23 17:27 UTC, merged