chore-mobile: use mobile path aliases
iotaledger/firefly pull request #5922
Opened 2023-02-19 17:06 UTC by begonaalvarezd

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

This PR aims to use path aliases in the mobile folder, wherever possible. 
- Use already existing path aliases
- Create generic `@/*` alias for the local lib folder, eg `@/contexts/settings`, `@/routers`, ...

Please note that because we still use electron to run mobile, some tweaks need to be made in the local setup to have the aliases working locally.

Instructions:

`packages/desktop/tsconfig.json`
```
"@auxiliary/*": ["../shared/lib/auxiliary/*"],
"@contexts/*": ["../shared/lib/contexts/*"],
"@components": ["../mobile/components"],
"@core/*": ["../shared/lib/core/*"],
"@features/*": ["../mobile/features/*"],
"@lib/*": ["../shared/lib/*"],
"@ui": ["../shared/components"],
"@ui/*": ["../shared/components/*"],
"@views": ["../mobile/views"],
"@/*": ["../mobile/lib/*"],
```

`packages/desktop/webpack.config.js`
```
svelte: path.dirname(require.resolve('svelte/package.json')),
'@auxiliary': path.resolve(__dirname, '../shared/lib/auxiliary'),
'@contexts': path.resolve(__dirname, '../shared/lib/contexts'),
'@components': path.resolve(__dirname, '../mobile/components/'),
'@core': path.resolve(__dirname, '../shared/lib/core'),
'@features': path.resolve(__dirname, '../mobile/features'),
'@lib': path.resolve(__dirname, '../shared/lib'),
'@ui': path.resolve(__dirname, '../shared/components/'),
'@views': path.resolve(__dirname, '../mobile/views/'),
'@': path.resolve(__dirname, '../mobile/lib/'),
```

## Changelog

```
- chore-mobile: use mobile path aliases
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-02-22 22:34 UTC, maxwellmattryan requested changes
Looks good! Will approve once conflicts are resolved :pray:

2023-02-23 12:22 UTC, paul-boegelsack approved these changes

2023-02-23 14:08 UTC, jeeanribeiro approved these changes

2023-02-23 22:26 UTC, maxwellmattryan approved these changes
LGTM :fire:

2023-02-24 08:22 UTC, merged