fix: capacitor api wallet plugin
iotaledger/firefly pull request #6199
Opened 2023-03-16 17:01 UTC by amadeu2

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.
Closes [#6170](https://github.com/iotaledger/firefly/issues/6170)

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-03-23 09:28 UTC, begonaalvarezd requested changes
Im able to install the app in my android phone but I am getting some errors when I start the app and try to login
`logAndNotifyError.ts:15 manager.getNodeInfo is not a function`
&
`Uncaught (in promise) TypeError: manager.stopBackgroundSync is not a function`
🙏🏼

2023-03-23 11:57 UTC, amadeu2 commented
> 



> Im able to install the app in my android phone but I am getting some errors when I start the app and try to login `logAndNotifyError.ts:15 manager.getNodeInfo is not a function` & `Uncaught (in promise) TypeError: manager.stopBackgroundSync is not a function` 🙏🏼

The instructions for tersting this branch is on this PR description. Like the PRs that were merged yesterday, they needed to be tested the `test/mobile-stardust` branch.
We've been talking on discord about this issue, we should not delay this merge, it's needed to work on the mobile folder easier.

2023-03-23 19:09 UTC, amadeu2 commented
> CI tests, format & type check are failing. Could you have a look at those?

Seems the problems on the CI started when I added "mobile" to the main `package.json`, and `engineStrict` was the guilty here. Just in case have reviewed and paired the `package.json` files between desktop and mobile folders

2023-03-27 10:36 UTC, begonaalvarezd approved these changes

2023-03-27 10:36 UTC, merged