fix: disable vote button after voting
iotaledger/firefly pull request #6317
Opened 2023-03-30 16:33 UTC by jeeanribeiro

## Summary
closes #6184 

## Testing

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [x] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented on my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-03-30 23:04 UTC, maxwellmattryan reviewed
Perhaps this is just on my machine with my network connection, but there's a small window of time from when the spinner stops after voting and the button is disabled (< 1s), then it becomes disabled and the answer starts pulsing. This allows me to still vote if I am fast enough to click the "Vote" button

2023-04-03 08:45 UTC, Tuditi requested changes
If I click on a Proposal that I voted on the following happens:

1) While the proposal status/answer is loading the submit vote button is active
2) Once everything is loaded the vote button becomes deactivated.

I think during 1) the button should be inactive, so we should add a condition that the button is only active if the proposal has been loaded.

2023-04-04 10:11 UTC, Tuditi requested changes
I added a suggestion

2023-04-04 13:43 UTC, maxwellmattryan reviewed
Left a suggestion

2023-04-04 13:43 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
> +        isSelectedEqualVotedAnswers
This name is just slightly unclear, maybe something like `areSelectedAndVotedAnswersEqual` or `hasSelectedNoNewAnswers` - I might be being a bit pedantic here :sweat_smile:

2023-04-04 19:13 UTC, maxwellmattryan commented
One last piece of feedback before I think it's ready to be merged:

When I click the "Stop voting" button, the spinner shows for both this and the "Vote" button instead of just showing for the "Stop voting" button while keeping the "Vote" button disabled. There was also 1-2 seconds after stopping a vote where the "Stop voting" button was active / "Vote" was disabled then it switched.

2023-04-05 20:21 UTC, maxwellmattryan requested changes
One requested change :pray:

2023-04-05 20:21 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
> +    let lastAction: 'vote' | 'stopVote'
We have a [`GovernanceAction`](https://github.com/iotaledger/firefly/blob/develop/packages/shared/lib/core/wallet/enums/governance-action.enum.ts) enum we should use here.

2023-04-05 21:10 UTC, maxwellmattryan commented
Some minor feedback:
- When I voted, I had to re-navigate back to the proposal details view for the "Stop voting" button to become enabled. Once the tx confirmed and the pulsing icons showed up, the "Stop voting" button was disabled along with the "Vote" button.
- I stopped voting then voted again for a proposal (without changing views), but the pulsing icons didn't show up until I re-navigated back to that view.

2023-04-06 00:14 UTC, maxwellmattryan approved these changes
Working like a charm :fire:

2023-04-06 00:19 UTC, merged