enhancement: improve dropdown component quality
iotaledger/firefly pull request #6449
Opened 2023-04-11 09:22 UTC by nicole-obrien

## Changelog

```
- Refactor code
- Show label instead of value
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-04-11 23:44 UTC, maxwellmattryan requested changes
Have some requested changes - have to review the rest tomorrow :sweat_smile:

2023-04-11 23:44 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/settings/views/collectibles/MaxMediaSize.svelte
> +    function updateMediaSizeLimit(option: IDropdownChoice<number>): void {
This should be named `onUpdateMediaSizeLimitClick`

2023-04-11 23:44 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/settings/views/general/Language.svelte
> +    function handleLanguage(item: IDropdownChoice<string>): void {
`onLanguageClick`

2023-04-11 23:44 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/settings/views/profile/Currency.svelte
> +    function handleCurrencySelect(item: IDropdownChoice<MarketCurrency>): void {
`onCurrencySelectClick`

2023-04-11 23:44 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/settings/views/security/AppLock.svelte
> +    function updateLockTimeout(option: IDropdownChoice<number>): void {
`onUpdateLockTimeoutClick`

2023-04-11 23:44 UTC, maxwellmattryan commented on packages/desktop/views/dashboard/settings/views/security/StrongholdPasswordTimeout.svelte
> +    function onSelect(option: IDropdownChoice<number>): void {
`onTimeoutSelectClick`

2023-04-12 12:27 UTC, MarkNerdi approved these changes
LGTM :fire:

2023-04-12 12:29 UTC, merged