enhancement: merge welcome and legal
iotaledger/firefly pull request #6507
Opened 2023-04-12 23:07 UTC by nicole-obrien

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-04-13 21:02 UTC, maxwellmattryan reviewed
Have a few requested changes :pray:

2023-04-13 21:02 UTC, maxwellmattryan commented on packages/shared/components/inputs/Checkbox.svelte
> +    import { Icon, Text, TextType } from 'shared/components'
`@ui`

2023-04-13 21:02 UTC, maxwellmattryan commented on packages/shared/lib/core/app/constants/index.ts
> +export * from './privacy-policy-link.constant'
We should use `URL` in the naming as we've never used "link"

2023-04-13 21:02 UTC, maxwellmattryan commented on packages/shared/lib/core/app/constants/privacy-policy-link.constant.ts
> +export const PRIVACY_POLICY_LINK = 'https://firefly.iota.org/privacy'
See naming comment above ^

2023-04-13 21:02 UTC, maxwellmattryan commented on packages/shared/lib/core/app/constants/terms-of-service-link.constant.ts
> +export const TERMS_OF_SERVICE_LINK = 'https://firefly.iota.org/terms'
See naming comment above ^

2023-04-13 22:12 UTC, nicole-obrien commented on packages/desktop/views/onboarding/views/app-setup/AppSetupRouter.svelte
> +    import { Transition } from 'shared/components'
ahh i just organised existing imports 🙄 😆

2023-04-18 07:52 UTC, Tuditi requested changes
One change requested, otherwise works fine! :relaxed:

2023-04-18 07:52 UTC, Tuditi commented on packages/desktop/views/onboarding/views/app-setup/views/WelcomeView.svelte
> +                >
Shouldn't this be localized?

2023-04-18 08:14 UTC, Tuditi commented on packages/desktop/views/onboarding/views/app-setup/views/WelcomeView.svelte
> +                >
As discussed on Discord, we don't know the locale at the start-up, so we have to rethink the localization of the welcome page if we want to support more languages.

2023-04-18 08:14 UTC, Tuditi approved these changes
:fire:

2023-04-18 08:15 UTC, merged