fix: clear password before backup
iotaledger/firefly pull request #6521
Opened 2023-04-13 15:10 UTC by jeeanribeiro

## Summary
This PR clears stronghold password from memory before trying to export stronghold backup

## Testing

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

## Checklist
-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-04-13 15:22 UTC, begonaalvarezd requested changes
unfortunately doesnt seem working for me, it looks like its because the store `isStrongholdLocked` is not updated, see the behavior here `packages/shared/lib/core/profile/actions/active-profile/unlockStronghold.ts` 🙏🏼

2023-04-14 16:49 UTC, begonaalvarezd requested changes
unfortunately i still get the same behavior. 
Couldnt we check on mobile directly to not change desktop's behavior? Just a though though, no need to do it that way

2023-04-19 22:51 UTC, jeeanribeiro commented
This needs to be fixed in iota-sdk as this is related to the "sendMessage" function error handling

2023-04-19 22:51 UTC, closed without merging

2023-04-19 22:54 UTC, jeeanribeiro commented
Being fixed in https://github.com/iotaledger/iota-sdk/tree/fix/capacitor-reject-promise-on-error