enhancement: add chain validation
iotaledger/firefly pull request #6576
Opened 2023-04-18 15:17 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-04-18 20:23 UTC, nicole-obrien submitted a review, later dismissed

2023-04-18 20:23 UTC, nicole-obrien commented on packages/desktop/components/drawers/network-config/drawers/AddChainDrawer.svelte
> +        if (!isHex || !/^(0x08)?[0-9a-f]{64}?(?:0[1-9]|[1-5][0-9]|6[0-4])?0{8}$/i.test(chain.aliasAddress)) {
Can we make a util for this?

2023-04-19 18:26 UTC, maxwellmattryan requested changes
Have some requested changes :pray:

2023-04-19 18:26 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/AddChainDrawer.svelte
> +        validate()
Probably should just make this function `void` and get rid of a few lines

2023-04-19 18:26 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/AddChainDrawer.svelte
>      <form id="add-chain-form" class="flex flex-col gap-3" on:submit|preventDefault={handleSubmit}>
Let's go ahead and make the `AddIscpChainForm` component and put the validation logic in there - will help with the upcoming tasks around this `AddChainDrawer` :+1:

2023-04-19 18:26 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/AddChainDrawer.svelte
>      function handleSubmit(): void {
Should be `onSubmitClick`

2023-04-20 21:19 UTC, maxwellmattryan requested changes
Some minor changes :pray:

2023-04-20 21:19 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/components/AddIscpChainForm.svelte
> +        } else if (chain.name.length > 64) {
Let's make this a constant i.e. `MAX_CHAIN_NAME_LENGTH`

2023-04-20 21:19 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/components/AddIscpChainForm.svelte
> +    function onSubmit(): void {
Should be `onSubmitClick`

2023-04-20 21:19 UTC, maxwellmattryan commented on packages/shared/lib/core/utils/crypto/utils/isValidHexAddress.ts
> +    return isHex && !/^(0x08)?[0-9a-f]{64}?(?:0[1-9]|[1-5][0-9]|6[0-4])?0{8}$/i.test(text)
Might be good to extract the regexp into a const, i.e.
```typescript
export const HEX_REGEXP = /^(0x08)?[0-9a-f]{64}?(?:0[1-9]|[1-5][0-9]|6[0-4])?0{8}$/i
```

2023-04-20 21:19 UTC, maxwellmattryan commented on packages/shared/lib/core/utils/crypto/utils/isValidHexAddress.ts
> +    return isHex && !/^(0x08)?[0-9a-f]{64}?(?:0[1-9]|[1-5][0-9]|6[0-4])?0{8}$/i.test(text)
We just need to be careful about the `/i` part at the end if we do make it a constant b/c the state is stored in the regexp so as long as we test wrong inputs multiple times back to back, should be alright

2023-04-20 21:19 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/components/AddIscpChainForm.svelte
> +    const isBusy = false
Should be `let` but irrelevant at this point

2023-04-21 19:43 UTC, maxwellmattryan requested changes
Two minor changes :pray:

2023-04-21 19:43 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/components/AddIscpChainForm.svelte
> +        validateExplorerUrl()
I think part of the validation should include if either the name or alias address is already being used. The explorer URL is fine and the ISCP endpoint is fine so long as the alias address is different.

2023-04-21 19:43 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/components/AddIscpChainForm.svelte
> +    import { ChainType } from '@core/network/enums'
Should be able to import this with the other stuff from `@core/network`

2023-04-21 19:44 UTC, maxwellmattryan commented on packages/desktop/components/drawers/network-config/drawers/components/AddIscpChainForm.svelte
> +        validateExplorerUrl()
Might be difficult to test that logic but the logic itself should be straightforward, might change slightly once we add the classes in :sweat_smile:

2023-04-26 14:23 UTC, maxwellmattryan reviewed
One question :thinking:

2023-04-26 14:23 UTC, maxwellmattryan commented on packages/shared/locales/en.json
> +                            "aliasAddressMustBeHex": "Alias address must be in hex format",
Is this true? I thought it was Bech32 encoding?

2023-04-29 00:37 UTC, maxwellmattryan approved these changes
LGTM :fire:

2023-04-29 00:41 UTC, merged