Feat/select asset popup
iotaledger/firefly pull request #6705
Opened 2023-05-02 06:32 UTC by MarkNerdi

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-05-03 22:20 UTC, maxwellmattryan requested changes
The code all looks good, just have some UX feedback:
- The search input should work with token names _and_ tickers
- When I use the search input, I feel it should deselect the selected token... if you have search input such that the selected token doesn't show, it is still possible to continue which feels strange.

2023-05-05 08:09 UTC, nicole-obrien requested changes

2023-05-05 08:09 UTC, nicole-obrien commented on packages/desktop/views/dashboard/send-flow/views/SelectTokenView.svelte
> +<select-asset-popup class="w-full h-full space-y-6 flex flex-auto flex-col flex-shrink-0">
select-token-view

2023-05-05 08:09 UTC, nicole-obrien commented on packages/desktop/views/dashboard/send-flow/views/SelectTokenView.svelte
> +    <select-token-buttons class="w-full space-y-4">
select-token-content

2023-05-08 13:55 UTC, MarkNerdi commented on packages/desktop/views/dashboard/send-flow/views/SelectTokenView.svelte
> +        }
if we filter the list and the once selected asset isnt included in that filtered list, we want to unset it and force the user to select a new one.

if the selected one is still in it, then we dont want to unselect it

2023-05-09 08:52 UTC, merged