feat: add logic / improve UX for `SaveBackupView`
iotaledger/firefly pull request #6743
Opened 2023-05-05 20:11 UTC by maxwellmattryan

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

This PR is mostly UX polish for the flow.

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-05-08 09:52 UTC, Tuditi requested changes
Requested some minor changes.

2023-05-08 09:52 UTC, Tuditi commented on packages/shared/routes/setup/import/views/Success.svelte
> +<OnboardingLayout allowBack={false}>
You should remove the `handleBackClick()` function as well if we don't allow the user to go back.

2023-05-09 12:37 UTC, Tuditi requested changes
I created some profiles with 1.7.1, but when I build this branch I receive the following error when I want to update the old profiles: 

`Stronghold migration error: Input snapshot has incorrect/unexpected version.`

2023-05-09 12:37 UTC, Tuditi commented on packages/shared/components/WarningBadge.svelte
> +    export let height = 38
Make these 32 and remove the props in `WarningBadge` :relaxed:

2023-05-09 12:40 UTC, Tuditi requested changes
Additionally I also get an error from `checkChrysalisSnapshot()` on start-up:

```
migration.ts:1221 SyntaxError: Unexpected token : in JSON at position 3
```

2023-05-09 13:49 UTC, maxwellmattryan commented
> Additionally I also get an error from checkChrysalisSnapshot() on start-up

Yeah that error has been there for a while I think - perhaps worth fixing in a separate PR. Will investigate though

2023-05-09 17:01 UTC, begonaalvarezd commented
> Additionally I also get an error from `checkChrysalisSnapshot()` on start-up:
> 
> ```
> migration.ts:1221 SyntaxError: Unexpected token : in JSON at position 3
> ```

I get this same issue also in v1.7.1 so perhaps is unrelated to this PR

2023-05-09 17:12 UTC, begonaalvarezd commented
> I created some profiles with 1.7.1, but when I build this branch I receive the following error when I want to update the old profiles:
> 
> `Stronghold migration error: Input snapshot has incorrect/unexpected version.`

I get the same issue if I only run yarn build && run start between versions, but you have to rebuild the entire backend, I usually run this from desktop to make sure I rebuild all `cd ../../ && yarn && cd packages/backend/bindings/node/ && yarn && cd ../../../desktop && yarn && yarn build && yarn start`, after running the full command, i dont get the above mentioned issue. It looks like you were generating profiles with the new stronghold version but firefly didnt know about it, so its trying to migrate an already migrated profile

2023-05-10 08:48 UTC, begonaalvarezd reviewed
Works great for me 🚀 
Just added a mini comment

2023-05-10 08:48 UTC, begonaalvarezd commented on packages/shared/routes/update-stronghold/UpdateStrongholdRouter.svelte
> +    let hasChangedPassword = false
I think `hasChangedPassword` this is not used anymore

2023-05-10 13:11 UTC, Tuditi commented
> > I created some profiles with 1.7.1, but when I build this branch I receive the following error when I want to update the old profiles:
> > `Stronghold migration error: Input snapshot has incorrect/unexpected version.`
> 
> I get the same issue if I only run yarn build && run start between versions, but you have to rebuild the entire backend, I usually run this from desktop to make sure I rebuild all `cd ../../ && yarn && cd packages/backend/bindings/node/ && yarn && cd ../../../desktop && yarn && yarn build && yarn start`, after running the full command, i dont get the above mentioned issue. It looks like you were generating profiles with the new stronghold version but firefly didnt know about it, so its trying to migrate an already migrated profile

Yup, this seemed to be my issue. Works fine now for me :relaxed:

2023-05-12 07:10 UTC, Tuditi approved these changes
LGTM! :fire:

2023-05-12 07:11 UTC, merged