chore: update wallet bindings
iotaledger/firefly pull request #6966
Opened 2023-06-08 10:39 UTC by Tuditi

## Summary

Updates @iota/wallet to rc-36

...

## Changelog

```
- Updates @iota/wallet to rc-36
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-06-21 08:49 UTC, begonaalvarezd commented
`rc-36`-> `rc-39` seem to be unstable for now. We have to wait on new bindings to be released to be able to keep testing

2023-06-21 08:50 UTC, begonaalvarezd requested changes
`rc-36`-> `rc-39` seem to be unstable for now. We have to wait on new bindings to be released to be able to keep testing

2023-07-19 12:03 UTC, begonaalvarezd reviewed
added a mini naming comment

2023-07-19 12:03 UTC, begonaalvarezd commented on packages/shared/lib/core/wallet/actions/mintNativeToken.ts
> +        const CreateNativeTokenTransaction = await account.mintNativeToken(params, DEFAULT_TRANSACTION_OPTIONS)
```suggestion
        const createNativeTokenTransaction = await account.mintNativeToken(params, DEFAULT_TRANSACTION_OPTIONS)
```

2023-07-19 13:46 UTC, Tuditi commented
@brancoder , tests are failing due to enums being imported from '@iota/wallet'. You should import enums like from the following repository: '@iota/wallet/out/types'.

The reason is that the relative import from the line below is not correct anymore:

https://github.com/iotaledger/iota-sdk/blob/e6253342cd5d4571bb7c0c3775d4396d329dfcc5/bindings/nodejs-old/lib/bindings.ts#L8

2023-07-24 15:32 UTC, begonaalvarezd commented
Duplicate of https://github.com/iotaledger/firefly/pull/7269

2023-07-24 15:32 UTC, closed without merging