remove: evm addresses from account
iotaledger/firefly pull request #7022
Opened 2023-06-21 16:33 UTC by begonaalvarezd

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

Close https://github.com/iotaledger/firefly/issues/7021

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-06-23 09:42 UTC, brancoder requested changes
LGTM apart from the `getIscpTransferMethod.ts` file

2023-06-23 09:42 UTC, brancoder commented on packages/shared/lib/core/layer-2/utils/getIscpTransferMethod.ts
Should we remove this file(and all other places its used in) because changing  `evmAddress = null` makes it obsolete? I can see that its not removed in any of the subsequent PRs in the train.

2023-06-26 08:48 UTC, begonaalvarezd commented on packages/shared/lib/core/layer-2/utils/getIscpTransferMethod.ts
`getIscpTransferMethod` is used in `getEstimatedGasForTransferFromTransactionDetails` which is needed for L1-L2 transactions. We will need to cleanup that up when fixing https://github.com/iotaledger/firefly/issues/7032

2023-06-26 08:55 UTC, brancoder approved these changes
LGTM

2023-06-26 08:57 UTC, merged