Fix: Improve readability of node info metrics value
iotaledger/firefly pull request #7053
Opened 2023-06-28 13:20 UTC by evavirseda

## Summary

Closes #6899 

## Changelog

![image](https://github.com/iotaledger/firefly/assets/72078237/08444f24-abb2-4adf-be79-840bbf6c3177)

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-06-28 13:46 UTC, begonaalvarezd commented on packages/desktop/components/popups/NodeInfoPopup.svelte
> +                    {:else if typeof nodeInfoValue === 'boolean'}
I wouldnt add the logic here, there is a section specifically to preprocess the data, in `processNodeInfoMapTab`

You could do something like 

```ts
function processNodeInfoMapTab(
    _nodeInfoTab: NodeInfoTab,
    key: string
): { localeKey: string; nodeInfoValue: unknown } {
    const nodeInfoTabObject = NODE_INFO_TAB_MAP[_nodeInfoTab]
    const localeKey = nodeInfoTabObject[key].localeKey
    let nodeInfoValue = ''
    if (key === 'url') {
        nodeInfoValue = node?.url
    } else {
        nodeInfoValue = resolveObjectPath(nodeInfo, nodeInfoTabObject[key]?.nodeInfoPath, null)
        if (key === 'referencedRate') {
            let referencedRate = Number(nodeInfoValue)
            if (referencedRate >= 0) {
                nodeInfoValue = `${formatNumber(Math.min(referencedRate, 100), 1, 1)}%`
            } else {
                nodeInfoValue = ''
            }
        }
    }

    return {
        localeKey,
        nodeInfoValue,
    }
}
```
With this you shouldnt need any HTML changes nor the extra custom function `formatMetricWithOneDecimal` which feels also a bit redundant

2023-06-28 14:18 UTC, begonaalvarezd requested changes
almost there 🌷

2023-06-28 14:18 UTC, begonaalvarezd commented on packages/desktop/components/popups/NodeInfoPopup.svelte
> +            if (localeKey === 'metrics.referencedRate') {
I would use the key here and not the `localeKey`

```suggestion
            if (key === 'referencedRate') {
```

2023-06-28 14:18 UTC, begonaalvarezd commented on packages/desktop/components/popups/NodeInfoPopup.svelte
> +            if (localeKey === 'metrics.referencedRate') {
I would also round to 1 or 2 decimals the 2 first elements
![image](https://github.com/iotaledger/firefly/assets/3624944/b34dd5aa-9255-4ab9-858b-7eca664530cb)

2023-06-28 18:51 UTC, cpl121 reviewed
When the rate information is copied, it appears in the form of a percentage (%), whereas when the entire information is copied, it appears in the previous format. I'm not sure if updating the `nodeInfo` store with the new format to maintain the same formatting would be correct

It's just a suggestion, as I'm not sure if what I'm saying is correct

2023-06-29 08:19 UTC, begonaalvarezd commented
> When the rate information is copied, it appears in the form of a percentage (%), whereas when the entire information is copied, it appears in the previous format. I'm not sure if updating the `nodeInfo` store with the new format to maintain the same formatting would be correct
> 
> It's just a suggestion, as I'm not sure if what I'm saying is correct

I think its ok how it is now, we are beautifying it for presentational purposes but the copy information function uses a JSON that can be more technical and present the information directly fetched from the node

2023-06-29 08:20 UTC, cpl121 approved these changes
LGTM 🥇

2023-06-29 08:27 UTC, begonaalvarezd approved these changes
🚀

2023-06-29 08:27 UTC, merged