refactor: remove component `ResultsNotAvailableTooltip`
iotaledger/firefly pull request #7073
Opened 2023-07-03 09:04 UTC by VmMad

## Summary

Closes #7070 
Remove component `ResultsNotAvailableTooltip` as it's unnecessary

## Changelog

```
- Remove component ResultsNotAvailableTooltip
- Add mouse handlers to avoid eslint warnings
```

## Testing

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

UI should remain the same.

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-03 17:51 UTC, evavirseda requested changes
amazing jean, just one suggestion :pray:

2023-07-03 17:51 UTC, evavirseda commented on packages/shared/components/InformationTooltip.svelte
>          <Text fontWeight={FontWeight.semibold} fontSize="16" classes="mb-2">
instead of using `classes`, you could add `space-y-2` to the div

2023-07-04 10:32 UTC, evavirseda approved these changes
nice :rocket:

2023-07-04 13:56 UTC, begonaalvarezd requested changes
Very nice work 💪🏼 
I would try and using the new `InformationTooltip` in more places in the code, I think is a very good reusable component that can help us removing duplicated code and unifying the styles of the basic info tooltips 🙏🏼

2023-07-04 13:56 UTC, begonaalvarezd commented on packages/shared/components/InformationTooltip.svelte
>  <Tooltip {anchor} {position}>
I would add a restprops here just in case
```suggestion
<Tooltip {anchor} {position} {..$$restProps}>
```

2023-07-04 13:56 UTC, begonaalvarezd commented on packages/shared/components/InformationTooltip.svelte
> +        <Text fontWeight={FontWeight.semibold} fontSize="16">
I would use a txt type h4 here or similar to avoid custom sizing

2023-07-04 13:56 UTC, begonaalvarezd commented on packages/shared/components/InformationTooltip.svelte
>          <Text fontWeight={FontWeight.normal}>
lets add the text type p here, and perhaps you dont need the font weight

2023-07-04 15:29 UTC, begonaalvarezd requested changes
Amazing work, added a mini comment and we are ready to merge 👯

2023-07-04 15:29 UTC, begonaalvarezd commented on packages/shared/components/InformationTooltip.svelte
> +    export let position: Position = Position.Right
we could remove these 2 props

2023-07-04 15:41 UTC, evavirseda approved these changes
LGTM :astronaut: :rocket:

2023-07-04 15:59 UTC, begonaalvarezd approved these changes
🔥

2023-07-04 16:00 UTC, merged