refactor: remove `AccountAssetsList`
iotaledger/firefly pull request #7081
Opened 2023-07-03 16:37 UTC by VmMad

## Summary

Remove unnecessary component `AccountAssetsList`

## Changelog

```
- Delete AccountAssetsList.svelte
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-03 17:57 UTC, evavirseda requested changes
there's a corner missing to sweep :broom: :wink:

2023-07-03 17:57 UTC, evavirseda commented on packages/desktop/views/dashboard/wallet/Wallet.svelte
```suggestion
```

2023-07-03 17:57 UTC, evavirseda commented on packages/desktop/views/dashboard/wallet/Wallet.svelte
```suggestion
```

2023-07-04 10:35 UTC, evavirseda approved these changes
:rocket:

2023-07-04 16:06 UTC, begonaalvarezd approved these changes
🚀

2023-07-04 16:12 UTC, merged