refactor: move outside atoms
iotaledger/firefly pull request #7085
Opened 2023-07-04 09:29 UTC by evavirseda

## Summary

Closes #7084 

## Changelog

```
- Move badges, boxes, buttons, iconButtons, labels, pills, and tiles out of the /atoms folder
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-06 10:49 UTC, brancoder approved these changes
LGTM

2023-07-07 10:18 UTC, begonaalvarezd requested changes
The app crashes in this branch in the following places:
- click send
- click search in tx history 
- click manage voting power
- ...

There must be some imports that are not updated and its causing the app to crash 🙏🏼

2023-07-07 10:51 UTC, begonaalvarezd commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +    import { AddressBox } from 'shared/components'
lets get these imports together 🙏🏼 we can also use the alias `@ui` for the import `shared/components` which we should be using too I think

2023-07-07 10:51 UTC, begonaalvarezd commented on packages/desktop/components/popups/ReceiveAddressPopup.svelte
> +    import { AddressBox } from 'shared/components'
there are couple appearances in this PR about these 2 points

2023-07-07 16:06 UTC, VmMad approved these changes

2023-07-13 16:43 UTC, begonaalvarezd approved these changes
🔥 🚒

2023-07-13 16:43 UTC, merged