refactor: cleanup `BalanceSummaryRow` & `BalanceSummarySection`
iotaledger/firefly pull request #7093
Opened 2023-07-04 13:08 UTC by evavirseda

## Summary

Closes #7090 

## Changelog

```
- Cleanup and refactor `BalanceSummaryRow`
- Cleanup `BalanceSummaryRow`
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-04 16:41 UTC, VmMad requested changes

2023-07-04 16:41 UTC, VmMad commented on packages/shared/components/BalanceSummarySection.svelte
>          class="w-full flex flex-row flex-grow justify-between space-x-2 {hasChildren ? 'cursor-pointer ' : ''}"
```suggestion
        class="w-full flex flex-row flex-grow justify-between space-x-2"
        class:cursor-pointer={hasChildren}
```

2023-07-04 16:41 UTC, VmMad commented on packages/shared/components/BalanceSummarySection.svelte
> +        return formatTokenAmountBestMatch(amount, baseCoin?.metadata as TokenMetadata)
```suggestion
        return baseCoin?.metadata ? formatTokenAmountBestMatch(amount, baseCoin?.metadata) : ''
```

2023-07-04 16:41 UTC, VmMad commented on packages/shared/components/BalanceSummarySection.svelte
> +        return formatCurrency(getMarketAmountFromAssetValue(amount, baseCoin as IAsset))
```suggestion
        return baseCoin ? formatCurrency(getMarketAmountFromAssetValue(amount, baseCoin)) : ''
```

2023-07-04 16:41 UTC, VmMad commented on packages/shared/components/BalanceSummaryRow.svelte
> +    <div class={title ? 'flex flex-col space-y-0.5' : ''}>
```suggestion
    <div class={title ? 'flex flex-col space-y-0.5' : null}>
```

2023-07-06 10:38 UTC, brancoder approved these changes
LGTM

2023-07-07 15:03 UTC, VmMad approved these changes

2023-07-13 16:31 UTC, begonaalvarezd approved these changes
😸

2023-07-13 16:32 UTC, merged