refactor: cleanup `Icon`
iotaledger/firefly pull request #7111
Opened 2023-07-06 15:23 UTC by evavirseda

## Summary

Closes #7102 

## Changelog

```
- Cleanup Icon component
- Create IconBox component
- Add enums
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-07 10:32 UTC, begonaalvarezd requested changes
Amazing work, the code looks much better 💪🏼 
Added some comments to improve a bit more the code base 🙏🏼

2023-07-07 10:32 UTC, begonaalvarezd commented on packages/shared/components/IconBox.svelte
> +<script lang="ts">
I would rename this component to BoxedIcon and make it so its a component that uses Icon but wrapps it in a box, so you could use it like `<BoxedIcon classes="text-blue-200" boxClasses="bg-pink-100" icon={IconEnum.Lola} />`

2023-07-07 10:32 UTC, begonaalvarezd commented on packages/shared/components/Alert.svelte
> +    interface ToastStyle {
Lets add an empty space to separate the props for the interfaces 🙏🏼

2023-07-07 10:32 UTC, begonaalvarezd commented on packages/shared/components/inputs/Checkbox.svelte
> +            icon={checked
I would move this logic to the script section and make if a bit easier to read with if elses, its a bit hard to read with nested ? ? ?

2023-07-12 07:01 UTC, cpl121 requested changes
Nice job!
1 minimal comment

2023-07-12 08:44 UTC, evavirseda commented on packages/shared/components/atoms/MenuItem.svelte
>      export let icon: string = ''
sure :pray:

2023-07-12 09:09 UTC, cpl121 requested changes
In addition to changing the `string` to `iconEnum`, I think it would be necessary to update the places where the `icon` was passed as in `string`
`CollectibleDetailsMenu` and `ExpirationTimePickerMenu`,

2023-07-12 10:27 UTC, cpl121 approved these changes
Perfect 🥇

2023-07-13 16:07 UTC, merged