refactor: cleanup `NetworkIcon`
iotaledger/firefly pull request #7147
Opened 2023-07-10 17:42 UTC by evavirseda

## Summary

Closes #7146 

## Changelog

```
- cleanup and add missing types
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-11 14:02 UTC, VmMad commented on packages/shared/components/atoms/NetworkIcon.svelte
>  </network-icon>
I think this component can be refactored a bit more. The enum and the function are unnecessary. You can make a map and use the networkId to index it. 

```svelte
// ...
    $: backgroundColor = classesMap[networkId]?.backgroundColor ?? ''
    $: iconColor = classesMap[networkId]?.iconColor ?? ''

    const classesMap: { [key in NetworkId]?: Record<string, string> } = {
        [NetworkId.Iota]: {
            backgroundColor: 'bg-black',
            iconColor: 'text-white',
        },
        [NetworkId.Shimmer]: {
            backgroundColor: 'bg-shimmer-highlight',
            iconColor: 'text-black',
        },
        [NetworkId.Testnet]: {
            backgroundColor: 'bg-gray-400',
            iconColor: 'text-black',
        },
    }
</script>

<network-icon class={backgroundColor ? backgroundColor : null} class:outlined>
    <Icon {height} {width} icon={NETWORK_ICON_SVG[networkId]} classes={iconColor} />
</network-icon>
```

2023-07-13 16:09 UTC, VmMad commented on packages/shared/components/NetworkIcon.svelte
> +<network-icon class={backgroundColor ? backgroundColor : null} class:outlined>
```suggestion
<network-icon class={backgroundColor ?? null} class:outlined>
```

2023-07-13 16:10 UTC, VmMad commented on packages/shared/components/NetworkIcon.svelte
> +<network-icon class={backgroundColor ? backgroundColor : null} class:outlined>
or even better just change the reactive line `$: backgroundColor = classesMap[networkId]?.backgroundColor ?? null` so you can leave `class={backgroundColor}`

2023-07-13 17:08 UTC, VmMad requested changes

2023-07-13 17:08 UTC, VmMad commented on packages/shared/components/NetworkIcon.svelte
> +    <Icon {height} {width} icon={NETWORK_ICON_SVG[networkId]} classes="text-{iconColor}" />
you forgot :thinking:  

```suggestion
    <Icon {height} {width} icon={NETWORK_ICON_SVG[networkId]} classes={iconColor} />
```

2023-07-14 10:42 UTC, VmMad approved these changes
Nice and clean :broom:

2023-07-17 11:36 UTC, cpl121 approved these changes
Nice job! 🥇

2023-07-18 15:24 UTC, merged