refactor: cleanup `AssetIcon` & `AssetList`
iotaledger/firefly pull request #7196
Opened 2023-07-13 14:13 UTC by evavirseda

## Summary

Closes #7192 

## Changelog

```
- Cleanup AssetIcon and AssetList
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-17 12:29 UTC, VmMad requested changes

2023-07-17 12:29 UTC, VmMad commented on packages/shared/components/AssetIcon.svelte
> +    export let small: boolean = false
Wouldn't it be better to make this a `size` prop to avoid sending both of these at the same time?

2023-07-17 12:29 UTC, VmMad commented on packages/shared/components/AssetIcon.svelte
> +            <img src={assetLogoUrl} on:error={() => (assetLogoUrl = '')} alt={assetLogoUrl} class="w-full h-full" />
can you make a handler function for onError to avoid the eslint warning?

2023-07-17 12:29 UTC, VmMad commented on packages/shared/components/AssetList.svelte
function on line 34 needs a return type, and if you can, please make a handler for the `AssetTile` onClick to remove that eslint warning

2023-07-17 14:35 UTC, VmMad commented on packages/shared/components/AssetIcon.svelte
> +                assetIconColor = isBright(assetIconBackgroundColor) ? 'text-gray-800' : 'text-white'
this line is repeated 3 times so it can be deleted

2023-07-17 15:00 UTC, VmMad requested changes
`SelectedTokenDrawer` needs the `size` update

2023-07-17 15:14 UTC, evavirseda commented
> SelectedTokenDrawer

As `SelectedTokenDrawer` is a mobile drawer,  there is no need to update it :pray:

2023-07-17 15:24 UTC, VmMad approved these changes

2023-08-01 10:14 UTC, begonaalvarezd approved these changes

2023-08-01 10:22 UTC, merged