refactor: cleanup `DateInputButton` & `ExpirationTimePicker`
iotaledger/firefly pull request #7200
Opened 2023-07-13 14:42 UTC by evavirseda

## Summary

Closes #7199 

## Changelog

```
- Cleanup `DateInputButton` & `ExpirationTimePicker`
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-13 15:22 UTC, marc2332 approved these changes

2023-07-17 13:50 UTC, VmMad requested changes

2023-07-17 13:50 UTC, VmMad commented on packages/shared/components/ExpirationTimePicker.svelte
> +        }
not necessary

2023-07-17 13:50 UTC, VmMad commented on packages/shared/components/ExpirationTimePicker.svelte
> +    export let value: Date | undefined | null = undefined
```suggestion
    export let value: Date | null = null
```

2023-07-17 15:03 UTC, VmMad approved these changes
Nice

2023-07-19 07:17 UTC, marc2332 commented
conflicts @evavirseda

2023-07-19 08:08 UTC, marc2332 approved these changes

2023-08-01 10:36 UTC, merged