feat: cleanup `QR`
iotaledger/firefly pull request #7231
Opened 2023-07-17 12:27 UTC by evavirseda

## Summary

Closes #7227 

## Changelog

```
- Cleanup QR
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-17 14:31 UTC, VmMad requested changes

2023-07-17 14:31 UTC, VmMad commented on packages/shared/components/QR.svelte
>      }
you can remove this style tag

2023-07-17 14:31 UTC, VmMad commented on packages/shared/components/QR.svelte
In this component, just change the line 17 to `padding: null` instead of `0` and the qr will be centered automatically.

2023-07-17 14:31 UTC, VmMad commented on packages/shared/components/QR.svelte
This way you can remove the styles tag, and change the size to 135

2023-07-17 14:35 UTC, marc2332 approved these changes

2023-07-17 15:19 UTC, VmMad approved these changes
Looks purrrfect :smiley_cat:

2023-08-01 12:35 UTC, begonaalvarezd requested changes
the QR is not centered anymore in the container box, the symetry is lost 🙏🏼 
![image](https://github.com/iotaledger/firefly/assets/3624944/8f91677a-5c51-444b-b54c-4879066210df)

2023-08-18 13:47 UTC, cpl121 approved these changes

2023-08-19 17:01 UTC, begonaalvarezd approved these changes
🚀

2023-08-19 17:01 UTC, merged