refactor: cleanup `Box`
iotaledger/firefly pull request #7240
Opened 2023-07-18 09:35 UTC by evavirseda

## Summary

Closes #7239 

## Changelog

```
- Cleanup Box
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-18 17:33 UTC, cpl121 requested changes

2023-07-18 17:33 UTC, cpl121 commented on packages/shared/components/boxes/CopyableBox.svelte
> -    export let classes = ''
When removing `classes` and `clearBoxPadding` from here, I think that in the `KeyValueBox` component it should also be removed
This change would also affect all sites where `KeyValueBox` is used 😅

2023-08-24 08:48 UTC, cpl121 approved these changes

2023-08-24 10:12 UTC, VmMad requested changes
There seems to be changes in the following places:

The search box now looks weird
![image](https://github.com/iotaledger/firefly/assets/88061365/43130108-5f85-4d3c-8804-9a456a1fc9fe)
Original:
![image](https://github.com/iotaledger/firefly/assets/88061365/67e8dacb-423b-4aed-9bb5-5d1d03dbdbc5)

Same thing happens to amount input in the filters, and the change profile name in settings.

Tabs in node information (settings) looks weird too: (PR)
![image](https://github.com/iotaledger/firefly/assets/88061365/2e79b5fb-6776-4092-8028-c7a593abfbe4)
(Original)
![image](https://github.com/iotaledger/firefly/assets/88061365/fb06784e-4159-4200-893a-f189d6f72b81)

And password inputs
![image](https://github.com/iotaledger/firefly/assets/88061365/86c80dd6-ffb9-4b9e-9349-e0b6d7d12699)

2023-08-25 11:36 UTC, VmMad requested changes
just a few changes, so that the component is cleaned up a little more

2023-08-28 08:32 UTC, VmMad requested changes
for some reason the amount filter looks bigger now
![image](https://github.com/iotaledger/firefly/assets/88061365/c26e7de4-3cc3-4689-8043-777400928a97)
![image](https://github.com/iotaledger/firefly/assets/88061365/0abd0f3e-6976-43a5-a107-d23bb37d1768)

2023-08-29 08:44 UTC, VmMad approved these changes
I think this is ready to go

2023-08-29 09:19 UTC, merged