refactor: cleanup `ExportStrongholdButton`
iotaledger/firefly pull request #7250
Opened 2023-07-19 12:38 UTC by evavirseda

## Summary

Closes #7249 

## Changelog

```
- cleanup ExportStrongholdButton
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-07-24 11:23 UTC, VmMad requested changes
Props have weird names imo

2023-07-24 11:23 UTC, VmMad commented on packages/desktop/views/dashboard/settings/views/security/ExportStronghold.svelte
> +    let exportMessage: string = ''
```suggestion
    let isBusy: boolean = false
    let message: string = ''
```

2023-07-24 11:23 UTC, VmMad commented on packages/shared/components/buttons/ExportStrongholdButton.svelte
> +    export let overrideTitle: string = ''
```suggestion
    export let title: string = ''
```

2023-08-04 09:57 UTC, cpl121 approved these changes
NJ

2023-08-19 17:05 UTC, begonaalvarezd approved these changes

2023-08-19 17:05 UTC, merged