chore(deps): bump svelty-picker from 3.6.1 to 4.1.4
iotaledger/firefly pull request #7381
Opened 2023-08-31 09:20 UTC by VmMad

## Summary

> bump svelty-picker version and cleanup DateTimePicker

## Changelog

```
- Remove unused css vars
- Cleanup DateTimePicker types and code composition
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

...

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-09-11 14:23 UTC, begonaalvarezd requested changes
Very good work, added some comments
Additionally, I cant install the app with the changes, it errors 🙏🏼

2023-09-11 14:23 UTC, begonaalvarezd commented on packages/shared/components/inputs/DateTimePicker.svelte
> +    export let startDate: Date | null = null
couldnt we unify these to be undefined or null both?

2023-09-11 14:23 UTC, begonaalvarezd commented on packages/shared/components/inputs/DateTimePicker.svelte
> +    let sveltyPickerDate = value ? convertDateToSveltyPickerFormat(value) : sveltyPickerStartDate
with null/undefined types unified you can simplify this too and leave it as it was before

2023-09-11 14:23 UTC, begonaalvarezd commented on packages/shared/components/inputs/DateTimePicker.svelte
> +        return date ? date?.toLocaleString('sv') : undefined
same here, no need to `date ? date?.`, eg
```suggestion
    function convertDateToSveltyPickerFormat(date: Date | undefined): string | undefined {
        return date?.toLocaleString('sv') ?? undefined
```

2023-09-11 14:23 UTC, begonaalvarezd commented on packages/shared/components/inputs/DateTimePicker.svelte
> +        if (sveltyPickerDate) {
if there is no date delected you can press confirm or the action will do nothing, I guess we should allow proceeding even if here is no date selected, you can set nothing

2023-10-18 07:51 UTC, cpl121 requested changes
![image](https://github.com/iotaledger/firefly/assets/100352899/d75561a8-49a6-4219-bced-aeb07de8bd66)

The current date does not appear marked when I open the popup
Also, I have the application in English and the date appears in Spanish

2023-10-18 08:46 UTC, VmMad commented
> ![image](https://user-images.githubusercontent.com/100352899/276154445-d75561a8-49a6-4219-bced-aeb07de8bd66.png)
> 
> The current date does not appear marked when I open the popup Also, I have the application in English and the date appears in Spanish

@cpl121 did you run `yarn install` before testing the PR? because I upgraded the version and the style variables changed and you probably didnt sync the package. For me the selected day shows up, and the problem with the spanish picker is the reactivity problem with i18n, because I didn't change anything and for me it shows in english. Try starting the dev server from zero. `yarn && cd packages/desktop && yarn && yarn build && yarn start`

![Screenshot from 2023-10-18 10-45-37](https://github.com/iotaledger/firefly/assets/88061365/1938c821-daf5-4af9-9f46-2262d1df98ab)

2023-10-18 08:58 UTC, cpl121 commented
> > ![image](https://user-images.githubusercontent.com/100352899/276154445-d75561a8-49a6-4219-bced-aeb07de8bd66.png)
> > The current date does not appear marked when I open the popup Also, I have the application in English and the date appears in Spanish
> 
> @cpl121 did you run `yarn install` before testing the PR? because I upgraded the version and the style variables changed and you probably didnt sync the package. For me the selected day shows up, and the problem with the spanish picker is the reactivity problem with i18n, because I didn't change anything and for me it shows in english. Try starting the dev server from zero. `yarn && cd packages/desktop && yarn && yarn build && yarn start`
> 
> ![Screenshot from 2023-10-18 10-45-37](https://user-images.githubusercontent.com/88061365/276178503-1938c821-daf5-4af9-9f46-2262d1df98ab.png)

Yes, I have run the large command 🥲

2023-10-18 13:13 UTC, cpl121 approved these changes
Perfect!! 🔥

2023-10-19 15:31 UTC, begonaalvarezd approved these changes

2023-10-19 15:35 UTC, merged