fix: Update FAQ link
iotaledger/firefly pull request #7460
Opened 2023-09-26 14:53 UTC by marc2332

Closes https://github.com/iotaledger/firefly/issues/7459

2023-09-26 15:01 UTC, cpl121 approved these changes

2023-09-26 16:13 UTC, begonaalvarezd requested changes
Asked for the new url, not sure we should use this one

2023-10-27 07:56 UTC, begonaalvarezd commented on packages/shared/lib/contexts/settings/constants/faq-url.constant.ts
> +export const FAQ_URL = 'https://wiki.iota.org/get-started/faq/'
new url `https://firefly.iota.org/faq`

2023-10-30 07:05 UTC, cpl121 approved these changes

2023-10-30 09:08 UTC, begonaalvarezd approved these changes

2023-10-30 09:19 UTC, merged