Fix: Enhanced logic for identifying burned native tokens.
iotaledger/firefly pull request #7584
Opened 2023-10-12 11:34 UTC by brancoder

## Summary

Refactor `getBurnedNativeTokens` logic for identifying burned native tokens.
resolves #7107 

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-10-16 12:26 UTC, cpl121 approved these changes
Nice job!!
Works for me ✌🏼 
![image](https://github.com/iotaledger/firefly/assets/100352899/0edefa90-3e12-466d-aceb-1080548fe42e)

2023-10-17 09:08 UTC, begonaalvarezd requested changes
Very nice work 💪🏼 
Just a minor detail, I sent a native token to an NFT and it showed as burned 🙏🏼 https://explorer.shimmer.network/testnet/transaction/0xd348041e5134b5436bc7fe7df69da8e027c60eb5bce9d4d12775a47c698c6fce

2023-10-18 07:15 UTC, brancoder commented
> Very nice work 💪🏼 Just a minor detail, I sent a native token to an NFT and it showed as burned 🙏🏼 https://explorer.shimmer.network/testnet/transaction/0xd348041e5134b5436bc7fe7df69da8e027c60eb5bce9d4d12775a47c698c6fce ![image](https://user-images.githubusercontent.com/3624944/275776671-a7c880fd-579c-40be-aa72-612f24b3020b.png)

Created a task for this issue https://github.com/iotaledger/firefly/issues/7617

2023-10-18 08:14 UTC, begonaalvarezd approved these changes

2023-10-18 08:15 UTC, merged