feat: reduce ledger polling on heavy duty work like recover accounts
iotaledger/firefly pull request #7715
Opened 2023-11-14 12:06 UTC by begonaalvarezd

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

Close https://github.com/iotaledger/firefly/issues/7714

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-11-14 12:13 UTC, marc2332 requested changes

2023-11-14 12:13 UTC, marc2332 commented on packages/shared/lib/core/account/actions/findBalances.ts
> +    profileType = get(activeProfile)?.type
Let's try not to use global functions to store state between functions. If you want to get the profile Type in `findBalances` just call `get` on the store again.

2023-11-16 14:02 UTC, cpl121 submitted a review, later dismissed
Works, but I think it would be interesting to also add it to the shimmer claiming

2023-11-17 09:22 UTC, marc2332 requested changes

2023-11-17 09:22 UTC, marc2332 commented on packages/shared/lib/core/ledger/actions/pollLedgerNanoStatus.ts
> +            clearInterval(intervalTimer)
```suggestion
        if (timeoutTimer) {
            clearTimeout(intervalTimer)
```

2023-11-17 09:22 UTC, marc2332 commented on packages/shared/lib/core/ledger/actions/pollLedgerNanoStatus.ts
> +            intervalTimer = setTimeout(() => void pollingFunction(), currentPollInterval)
```suggestion
            timeoutTimer = setTimeout(() => void pollingFunction(), currentPollInterval)
```

2023-11-17 09:22 UTC, marc2332 commented on packages/shared/lib/core/ledger/actions/pollLedgerNanoStatus.ts
> +let intervalTimer: ReturnType<typeof setInterval> | null
```suggestion
let timeoutTimer: ReturnType<typeof setTimeout> | null
```

2023-11-17 15:40 UTC, marc2332 requested changes
sorry

2023-11-17 15:40 UTC, marc2332 commented on packages/shared/lib/core/ledger/actions/pollLedgerNanoStatus.ts
> +let timeoutTimer: ReturnType<typeof setInterval> | undefined
```suggestion
let timeoutTimer: ReturnType<typeof setTimeout> | undefined
```

2023-11-17 15:53 UTC, merged