Feat: Add "discover addresses" using a permanode
iotaledger/firefly pull request #7750
Opened 2023-11-29 10:25 UTC by msarcev

## Summary

- Generate addresses not known by the sdk or locally and query the address against a permanode to know if it had history
- Persist all known addresses in localStorage to save requests in the future
- Use gap logic in the search algorithm to know when to stop generating addresses

Resolves https://github.com/iotaledger/firefly/issues/7594

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [x] MacOS
    -   [ ] Linux
    -   [ ] Windows

2023-12-06 15:49 UTC, brancoder requested changes
Fix type check and lint errors

2023-12-06 15:49 UTC, brancoder commented on packages/desktop/components/popups/AddressHistoryPopup.svelte
> +        currendSearchGap = 0
fix typo in variable name `currentSearchGap`

2023-12-10 16:27 UTC, begonaalvarezd requested changes

2023-12-10 16:27 UTC, begonaalvarezd commented on packages/shared/lib/core/network/constants/chronicle-urls.constant.ts
> +    [NetworkId.Iota]: ['https://chronicle.stardust-mainnet.iotaledger.net/'],
the rotating addresses most likely come from chrysalis not stardust, shouldnt we check the historical addresses in chrysalis instead?

2023-12-10 16:30 UTC, begonaalvarezd requested changes

2023-12-10 16:30 UTC, begonaalvarezd commented on packages/desktop/components/popups/AddressHistoryPopup.svelte
> +            error = 'Chronicle not configured'
All error messages should be internationalized

2023-12-10 16:30 UTC, begonaalvarezd commented on packages/desktop/components/popups/AddressHistoryPopup.svelte
> +            error = 'Couldn\'t fetch address history'
All error messages should be internationalized

2023-12-10 16:30 UTC, begonaalvarezd commented on packages/desktop/components/popups/AddressHistoryPopup.svelte
> +            error = 'Couldn\'t generate a new address'
All error messages should be internationalized

2023-12-10 16:30 UTC, begonaalvarezd commented on packages/shared/lib/core/network/constants/chronicle-urls.constant.ts
> +    [NetworkId.Testnet]: ['https://chronicle.testnet.shimmer.network/'],
if we use chrysalis we can likely remove these

2023-12-11 14:52 UTC, msarcev commented
I had to modify `checkAndMigrateChrysalisProfiles` here for the new field in `IPersistedAccountData`. Please confirm that this is fine. :D

2023-12-12 15:47 UTC, begonaalvarezd approved these changes
🚀 works

2023-12-13 14:17 UTC, brancoder approved these changes
LGTM :+1:

2023-12-18 17:16 UTC, merged