feat: improve ipfs media download when file its in folder
iotaledger/firefly pull request #7752
Opened 2023-11-29 14:57 UTC by evavirseda

## Summary

> Closes #7689 

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-12-04 09:19 UTC, brancoder requested changes
There seams to be an issue with encoding this example `ipfs://bafybeigbmawzzda64hrr2zenodmivfandhkjsrf7nkcic52y5wb6nxywja`

2023-12-04 09:19 UTC, brancoder commented on packages/shared/lib/core/nfts/utils/getIpfsUri.ts
> +        const slicedLink = link.hash.slice('https://ipfs.io/'.length)
We could use the the constant `IPFS_ENDPOINT` here instead of hardcoded string

2023-12-04 09:19 UTC, brancoder commented on packages/shared/lib/core/nfts/actions/updateNftInAllAccountNfts.ts
> +            void getIpfsUri({ hash: downloadUrl }).then((ipfsUri) => {
Should we check if the `downloadUrl` is a ipfs link before calling `getIpfsUri` for every nft? wdyt?

2023-12-05 11:28 UTC, brancoder commented on packages/shared/lib/core/nfts/actions/updateNftInAllAccountNfts.ts
> +            if (downloadUrl) {
I was thinking something along the lines like this check we have in explorer: https://github.com/iotaledger/explorer/blob/dev/client/src/helpers/hooks/useNftMetadataUri.ts#L22
Looks to me that we now try to `getIpfsUri` even if `downloadUrl` is not ipfs link.

2023-12-10 16:21 UTC, begonaalvarezd commented
> There seams to be an issue with encoding this example `ipfs://bafybeigbmawzzda64hrr2zenodmivfandhkjsrf7nkcic52y5wb6nxywja`

This one is a folder inside a folder, I would ignore it, we should just check 1 level

2023-12-13 09:51 UTC, brancoder commented on packages/shared/lib/core/nfts/utils/getIpfsHash.ts
> +        return url.slice(ipfsPrefix.length)
This method now returns url with first 4 characters sliced ex. `s://ipfs.io/ipfs.......` instead of ipfs hash.

2023-12-13 09:55 UTC, brancoder approved these changes

2023-12-13 11:27 UTC, begonaalvarezd requested changes
Im requesting changes just to block this PR from being merged, I would like to have a security expert have a look at it before we add it to production builds 🙏🏼

2023-12-20 09:32 UTC, marc2332 requested changes

2023-12-20 09:32 UTC, marc2332 commented on packages/shared/lib/core/nfts/utils/getIpfsHash.ts
> +    const ipfsPrefix = 'https://ipfs.io'
There are other gateways apart from ipfs.io, this isn't very robust imo

2024-03-28 21:06 UTC, rajivshah3 commented on packages/shared/lib/core/nfts/utils/getIpfsHash.ts
> +        return url.slice(ipfsPrefix.length)
Would it be better to use the `URL` module so we can address this comment and @marc2332 's comment? If we have `https://cloudflare-ipfs.com/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` and we want to get the `bafy...` part I think we could do this:

```js
const ipfsUrl = new URL("https://cloudflare-ipfs.com/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html")
const path = ipfsUrl.pathname
return path.replace("/ipfs/", "").split("/")[0]
```

2025-05-02 13:40 UTC, marc2332 commented
🫡

2025-05-02 13:40 UTC, closed without merging