feat: update deeplinks docs
iotaledger/firefly pull request #7760
Opened 2023-12-04 11:07 UTC by evavirseda

## Summary

> Closes #7751 

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2023-12-04 14:53 UTC, marc2332 requested changes
Thoughts?

2023-12-04 14:53 UTC, marc2332 commented on docs/specifications/deep-links.md
I would call `SHIMMER` just `Shimmer

2023-12-04 14:53 UTC, marc2332 commented on docs/specifications/deep-links.md
```suggestion
To target the production version simply don't specify any stages, for example with Shimmer:

```

2023-12-21 08:15 UTC, cpl121 approved these changes
LGTM

2024-01-16 15:04 UTC, marc2332 approved these changes

2024-01-25 15:59 UTC, merged