feat: add implicit account creation router
iotaledger/firefly pull request #7815
Opened 2023-12-22 16:10 UTC by evavirseda

## Summary

> Closes #7811 

...

## Changelog

```
- Add new account route
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-01-03 11:22 UTC, cpl121 requested changes
some comments 🙏🏼

2024-01-03 11:22 UTC, cpl121 commented on packages/desktop/views/account/AccountRouter.svelte
> +<script lang="ts">
We would have to add a file `index.js` in `views/account`, then we could add `AccountRouter` to the import of `'@views'` in `packages/desktop/App.svelte`

2024-01-03 11:22 UTC, cpl121 commented on packages/shared/lib/core/router/enums/app-route.enum.ts
> +    Account = 'account',
I think the name may be more precise. What do you think of `implicitAccountCreation`?

2024-01-04 17:05 UTC, cpl121 requested changes
NJ!

2024-01-04 17:05 UTC, cpl121 commented on packages/desktop/App.svelte
> +    import { OnboardingRouterView, ImplicitAccountCreationRouterView } from '@views'
Duplicate this import `from '@views'`

2024-01-05 12:32 UTC, cpl121 approved these changes
NJ

2024-01-09 17:17 UTC, begonaalvarezd requested changes
explained what needs to be updated to @cpl121 please discuss with him what needs to be updated
sorry sorry 💔💔 💔

2024-01-10 16:37 UTC, begonaalvarezd requested changes

2024-01-10 16:37 UTC, begonaalvarezd commented on packages/desktop/views/dashboard/wallet/Wallet.svelte
> +    const hasImplicitAccount: boolean = false
```suggestion
    const hasAccount: boolean = false
```

2024-01-10 16:37 UTC, begonaalvarezd commented on packages/desktop/views/dashboard/wallet/Wallet.svelte
> +{#if hasImplicitAccount}
```suggestion
{#if hasAccount}
```

2024-01-10 16:37 UTC, begonaalvarezd approved these changes

2024-01-10 17:16 UTC, merged