feat: prepare UI for implicit account creation STEP 1
iotaledger/firefly pull request #7878
Opened 2023-12-27 10:15 UTC by evavirseda

## Summary

> Closes #7812 

...

## Changelog

```
- Prepare UI
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-01-03 11:58 UTC, cpl121 commented on packages/desktop/views/account/multi-step/ShowOneTimeAddress.svelte
> +    const DUMMY_ADDRESS = 'iota1q9f0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryjtzcp98'
The comment of the `onCopyClick` function should be put here, since the constant is not only used in the function

2024-01-10 17:35 UTC, begonaalvarezd commented on packages/desktop/views/dashboard/wallet/views/multi-step/OneTimeDeposit.svelte
> +    let isAddressShown: boolean = false
```suggestion
    let isVisibleAddress: boolean = false
```

2024-01-14 18:53 UTC, cpl121 requested changes

2024-01-14 18:53 UTC, cpl121 commented on packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/OneTimeDepositView.svelte
> +                src="assets/illustrations/implicit-account/show-one-time-address.svg"
```suggestion
                src="assets/illustrations/implicit-account-creation/step1.svg"
```

2024-01-14 18:55 UTC, cpl121 commented on packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/OneTimeDepositView.svelte
> +                src="assets/illustrations/implicit-account/show-one-time-address.svg"
Solved [here](https://github.com/iotaledger/firefly/pull/7879/files#diff-68b1f48167c80f3f6d472987a7fa710ef4590cfbdc0c2073591f2f49d32ed876R24)
🤐

2024-01-14 18:55 UTC, cpl121 approved these changes
LGTM

2024-01-16 09:52 UTC, begonaalvarezd approved these changes

2024-01-16 09:52 UTC, merged