feat: Prepare UI for implicit account creation STEP 3
iotaledger/firefly pull request #7880
Opened 2023-12-27 11:16 UTC by evavirseda

## Summary

> Closes #7814 

...

## Changelog

```
- Prepare UI step 3
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-01-03 13:06 UTC, cpl121 approved these changes
🚀

2024-01-16 10:06 UTC, begonaalvarezd requested changes

2024-01-16 10:06 UTC, begonaalvarezd commented on packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
> +    function activeAccount(): void {
```suggestion
    function unlockWalletAndCreateAccount(): void {
```

2024-01-16 10:06 UTC, begonaalvarezd commented on packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
> +    <Button onClick={activeAccount}>{localize('views.implicit-account-creation.steps.step2.view.action')}</Button>
```suggestion
    <Button onClick={unlockWalletAndCreateAccount}>{localize('views.implicit-account-creation.steps.step2.view.action')}</Button>
```

2024-01-16 10:06 UTC, begonaalvarezd approved these changes

2024-01-16 10:17 UTC, merged