Feat/update wallet state to accomodate accounts
iotaledger/firefly pull request #7890
Opened 2024-01-04 10:42 UTC by cpl121

Closes #7803

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-01-08 07:59 UTC, marc2332 submitted a review, later dismissed

2024-01-16 13:13 UTC, begonaalvarezd requested changes

2024-01-16 13:13 UTC, begonaalvarezd commented on packages/desktop/views/dashboard/wallet/Wallet.svelte
> +    const hasAccount: boolean = $selectedWallet.accountsOutput.length !== 0
It will probably benefit from being reactive
```suggestion
    $: hasAccount: boolean = $selectedWallet.accountsOutput.length !== 0
```

2024-01-16 13:13 UTC, begonaalvarezd commented on packages/shared/lib/core/wallet/actions/buildWalletState.ts
> +        accountsOutput = await wallet.accounts()
```suggestion
        accountOutputs = await wallet.accounts()
```

2024-01-16 13:13 UTC, begonaalvarezd commented on packages/shared/lib/core/wallet/actions/buildWalletState.ts
> +        implicitAccountsOutput = await wallet.implicitAccounts()
```suggestion
        implicitAccountOutputs = await wallet.implicitAccounts()
```

2024-01-16 14:06 UTC, marc2332 approved these changes
lgtm, just do what begoña said

2024-01-16 17:12 UTC, begonaalvarezd approved these changes
🔥

2024-01-16 17:12 UTC, merged