feat: update events to accomodate accounts WIP
iotaledger/firefly pull request #7895
Opened 2024-01-08 14:30 UTC by cpl121

Closes #7840

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-01-15 17:24 UTC, marc2332 requested changes

2024-01-15 17:24 UTC, marc2332 commented on packages/shared/lib/core/wallet/utils/validateWalletApiEvent.ts
I casually ended up fixing some of this code in my profile manager refactor PR

key points: 
- Events do no longer include any sort of ID, this must be passed manually, example: https://github.com/iotaledger/firefly/pull/7809/files#diff-b497998dedc3783a901118c29dd2b0064ac8d300f824684007ee90d10beaab38
- `Event` type is gone, use `WalletEvent`.
- Example with [`handleNewOutputEvent`](https://github.com/iotaledger/firefly/pull/7809/files#diff-5790b75f3a351fa8556f6c427a234a781582ce1342b29dd6914d80c2da3fba84)
- [`validateWalletApiEvent`](https://github.com/iotaledger/firefly/pull/7809/files#diff-bdd4828996ff171206b613773bb132f2f640e745c415c629f84669c5f1714113)

2024-01-16 14:28 UTC, marc2332 requested changes

2024-01-16 14:28 UTC, marc2332 commented on packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
> +    onDestroy(unsubscribeFromWalletApiEvents)
let's put this on `ImplicitAccountCreationView.svelte`.

2024-01-16 16:13 UTC, marc2332 requested changes

2024-01-16 16:13 UTC, marc2332 commented on packages/shared/lib/contexts/wallet/implicit-account-creation/actions/handleNewOutputForImplicitAccountCreation.ts
> +export async function handleNewOutputForImplicitAccountCreationInternal(
Let's get rid of this, I would move this logic to `handleNewOutputEventInternal.ts`

2024-01-16 16:13 UTC, marc2332 commented on packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
> +    onDestroy(unsubscribeFromWalletApiEvents)
also remove this line

2024-01-16 16:13 UTC, marc2332 commented on packages/desktop/views/dashboard/wallet/views/ImplicitAccountCreationView.svelte
> +    onMount(subscribeToWalletApiEventsForImplicitAccountCreation)
and this one

2024-01-16 16:13 UTC, marc2332 commented on packages/shared/lib/contexts/wallet/implicit-account-creation/actions/subscribeToWalletApiEventsForImplicitAccountCreation.ts
and this as well

2024-01-17 07:40 UTC, marc2332 approved these changes
:fire:

2024-01-17 09:36 UTC, marc2332 commented on packages/desktop/views/dashboard/wallet/views/ImplicitAccountCreationView.svelte
> +    onMount(subscribeToWalletApiEventsForImplicitAccountCreation)
that's old code, refresh the changes

2024-01-18 17:20 UTC, begonaalvarezd requested changes

2024-01-18 17:20 UTC, begonaalvarezd commented on packages/shared/lib/core/wallet/actions/events-handlers/handleNewOutputEvent.ts
> +    const isImplicitAccountOutput =
its missing to check that the address unlock condition belongs to the implicit account address, you can do so  by checking that the address unlock condition is your implicit account creation address, or by checking the type of that address

2024-01-19 16:21 UTC, begonaalvarezd approved these changes

2024-01-19 16:21 UTC, merged