feat: update deposit address to selected created explicit account
iotaledger/firefly pull request #7907
Opened 2024-01-18 12:54 UTC by evavirseda

## Summary

> Closes #7846 

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-01-19 16:14 UTC, cpl121 commented on packages/shared/lib/core/wallet/utils/getDepositAddress.ts
> +        // TODO: when we have selectedAccount in the store,  we need to find the account with the blockIssuer feature
Duplicate TODO comment

2024-01-19 16:15 UTC, cpl121 requested changes

2024-01-19 16:15 UTC, cpl121 commented on packages/shared/lib/core/wallet/utils/getDepositAddress.ts
> +        return depositAddress
```suggestion
        return (accounts[0]?.output as AccountOutput).accountId ?? ''
```

2024-01-19 16:21 UTC, cpl121 approved these changes
Perfect!

2024-01-22 11:57 UTC, begonaalvarezd requested changes
🙏🏼 little thing

2024-01-22 11:57 UTC, begonaalvarezd commented on packages/shared/lib/core/wallet/actions/buildWalletState.ts
> +        depositAddress = await getDepositAddress()
lets not remove this argument so we leave the function a bit more generic

2024-01-22 13:51 UTC, merged