feat: update dev tools faucet
iotaledger/firefly pull request #7929
Opened 2024-01-26 15:15 UTC by cpl121

Closes #7920

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-01-31 11:36 UTC, evavirseda approved these changes
looks good :+1:

2024-02-01 08:27 UTC, marc2332 requested changes

2024-02-01 08:27 UTC, marc2332 commented on packages/desktop/components/buttons/popup-buttons/FaucetRequestButton.svelte
> +            values: { network: $nodeInfo.protocolParameters?.[0]?.parameters?.networkName },
Wouldn't it be better to use `$nodeInfoNetworkName`?

2024-02-01 08:27 UTC, marc2332 commented on packages/desktop/components/popups/FaucetRequestPopup.svelte
> +                        network: $nodeInfo.protocolParameters?.[0]?.parameters?.networkName,
Same here

2024-02-01 08:51 UTC, marc2332 approved these changes

2024-02-02 18:36 UTC, merged