feat: update timelock unlock condition
iotaledger/firefly pull request #8007
Opened 2024-02-07 09:38 UTC by cpl121

Closes #7983 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-02-12 14:35 UTC, marc2332 requested changes

2024-02-12 14:35 UTC, marc2332 commented on packages/shared/lib/core/wallet/utils/outputs/isOutputTimeLocked.ts
> +        return timelockUnlockCondition.slotIndex + nodeProtocolParameters.minCommittableAge < 0
I don't think this makes sense, this is not the same as the rust [code](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/types/block/output/unlock_condition/timelock.rs#L34).

The correct (I Think) formula is: `(currentSlotIndex + minCommittableAge) < output.timelockUnlockCondition.slotIndex`

but you are doing: `(output.timelockUnlockCondition.slotIndex + + minCommittableAge) < 0`

If you think about it, you can't check if an output is locked if you don't even know at what moment you are when you check it.

2024-02-12 14:38 UTC, marc2332 commented on packages/shared/lib/core/wallet/utils/outputs/isOutputTimeLocked.ts
> +        return timelockUnlockCondition.slotIndex + nodeProtocolParameters.minCommittableAge < 0
From another POV, there is no way that your `(output.timelockUnlockCondition.slotIndex + minCommittableAge)` can ever be `< 0`

2024-02-12 14:42 UTC, marc2332 commented on packages/shared/lib/core/wallet/utils/outputs/isOutputTimeLocked.ts
> +        return timelockUnlockCondition.slotIndex + nodeProtocolParameters.minCommittableAge < 0
So I think the correct code would be something like 

```ts
(currentSlotIndex + nodeProtocolParameters.minCommittableAge) < timelockUnlockCondition.slotIndex
```

I don't know where you can't get `currentSlotIndex` from tho

2024-02-12 14:45 UTC, marc2332 commented on packages/shared/lib/core/wallet/utils/outputs/isOutputTimeLocked.ts
> +        return timelockUnlockCondition.slotIndex + nodeProtocolParameters.minCommittableAge < 0
Ah, I see there is `getSlotIndexFromNodeInfo` you can use that for `currentSlotIndex`

2024-02-13 15:39 UTC, marc2332 approved these changes
:godmode: :zap:  I approve this :+1: :deciduous_tree:

2024-02-16 11:36 UTC, begonaalvarezd approved these changes
🔥

2024-02-16 11:38 UTC, merged