feat: add account info UI
iotaledger/firefly pull request #8018
Opened 2024-02-08 18:37 UTC by evavirseda

## Summary

> Closes #7968 

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-02-12 13:24 UTC, cpl121 requested changes
2 minimal comments 🙏🏼

2024-02-12 13:24 UTC, cpl121 commented on packages/desktop/views/dashboard/account-management/AccountManagement.svelte
> +    const allAccounts: OutputData[] = [...accounts, ...implicitAccounts]
outdated

2024-02-12 13:24 UTC, cpl121 commented on packages/desktop/components/AccountManagementList.svelte
> +            address = getBech32AddressFromAddressTypes(
these changes are outdated respect to the base branch

2024-02-13 10:55 UTC, cpl121 approved these changes
LGTM

2024-02-13 11:10 UTC, marc2332 approved these changes

2024-02-13 12:18 UTC, merged