feat: Add link to legacy migration tool post
iotaledger/firefly pull request #8048
Opened 2024-02-14 16:07 UTC by evavirseda

## Summary

> Closes #7802 

...

## Changelog

```
- Add link to post in onboarding flow
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-02-15 07:44 UTC, marc2332 requested changes

2024-02-15 07:44 UTC, marc2332 commented on packages/desktop/views/onboarding/views/ChooseOnboardingFlowView.svelte
> +        const url = 'https://blog.iota.org/iota-legacy-migration-tool'
shouldn't we move this to a constant maybe?

2024-02-20 16:09 UTC, cpl121 approved these changes
Nice!

2024-02-20 16:23 UTC, marc2332 approved these changes

2024-02-22 18:26 UTC, begonaalvarezd approved these changes

2024-02-22 18:26 UTC, merged