feat: add staked amount to account management
iotaledger/firefly pull request #8056
Opened 2024-02-15 14:09 UTC by evavirseda

## Summary

> Closes #8045 

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-02-16 13:09 UTC, cpl121 approved these changes
Nice!!
It works with mocked data 🚀 
![Captura de pantalla de 2024-02-16 14-06-11](https://github.com/iotaledger/firefly/assets/100352899/61484f55-39ef-4ada-ab8d-40a8f652a18f)

2024-02-16 14:30 UTC, begonaalvarezd requested changes

2024-02-16 14:30 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +            amount = stakedFeature.stakedAmount.toString()
this can crash if there is no staking feature I think

2024-02-16 14:30 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +        if (isImplicitAccount) return amount + 'i'
what is `i`? the unit? we should not hardcode any unit, it should be taken from the network you are in

2024-02-16 14:30 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +    function hasOutputStakedFeature(output: OutputData): boolean {
```suggestion
    function hasStakingFeature(output: OutputData): boolean {
```

2024-02-16 14:30 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +        let amount = '0'
if there is no staking we should not display this at all, for implicit and for accounts without the staking feature enabled

2024-02-16 14:30 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +            const stakedFeature = accountOutput.features.find(
```suggestion
            const stakingFeature = accountOutput.features.find(
```

2024-02-19 09:44 UTC, begonaalvarezd requested changes

2024-02-19 09:44 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +    $: hasStakedFeature = hasStakingFeature(selectedOutput)
```suggestion
    $: hasStakingFeature = hasStakingFeature(selectedOutput)
```

2024-02-19 09:44 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +        if (!hasStakedFeature) return
```suggestion
        if (!hasStakingFeature) return
```

2024-02-19 09:44 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +                {#if hasStakedFeature}
```suggestion
                {#if hasStakingFeature}
```

2024-02-19 09:53 UTC, begonaalvarezd requested changes

2024-02-19 09:53 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +                            <Text type={TextType.h3}>{getStakedAmount()}</Text>
I would not use a function here for `getStakedAmount` but rather a reactive variable that updates when the output updates, we will need 2 new reactive variables, eg `rawStakedAmount` & `formattedStakedAmount`

2024-02-19 09:53 UTC, begonaalvarezd commented on packages/desktop/components/AccountManagementDetails.svelte
> +        let amount = '0'
Why amount is a string here, we pass it as string in `amount = stakingFeature?.stakedAmount?.toString()` but then we convert it to `Number` when we call `formatTokenAmountBestMatch`?

2024-02-19 14:35 UTC, begonaalvarezd approved these changes

2024-02-19 14:36 UTC, merged