feat: show BIC balance in account details
iotaledger/firefly pull request #8151
Opened 2024-03-06 19:18 UTC by cpl121

Closes #8145 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-03-11 11:34 UTC, marc2332 requested changes
wouldn't it better to keep things this simple

2024-03-11 11:34 UTC, marc2332 commented on packages/shared/lib/core/wallet/interfaces/extended-balance.interface.ts
> +    totalWalletBic?: number
```suggestion
    blockIssuanceCredits: { [accountId: string]: number }
    totalWalletBic: number
```

2024-03-11 11:34 UTC, marc2332 commented on packages/shared/lib/core/wallet/actions/syncBalance.ts
> +        ...(syncCongestion && !!totalWalletBic && { totalWalletBic }),
```suggestion
        ... { totalWalletBic, blockIssuanceCredits }
```

2024-03-11 11:34 UTC, marc2332 commented on packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/FundConfirmationView.svelte
> +            ($selectedWallet?.balances.totalWalletBic ?? 0) -
```suggestion
            ($selectedWallet?.balances.totalWalletBic) -
```

2024-03-18 15:55 UTC, evavirseda requested changes
Nice job, just a little detail:pray:

2024-03-18 15:55 UTC, evavirseda commented on packages/shared/locales/en.json
> +                "blockIssuanceCredits": "Block Issuance Credits Mana",
```suggestion
                "blockIssuanceCredits": "Block Issuance Credit (BIC)",
```

2024-03-18 16:31 UTC, evavirseda approved these changes
good job :rocket:

2024-03-19 10:20 UTC, begonaalvarezd requested changes
add logic to get BIC if there are explicit accounts to `buildWalletState.ts`

2024-03-19 15:53 UTC, begonaalvarezd approved these changes

2024-03-19 15:53 UTC, merged