fix: Remove PoW and debris
iotaledger/firefly pull request #8177
Opened 2024-03-08 10:19 UTC by marc2332

Closes https://github.com/iotaledger/firefly/issues/8176

2024-03-13 09:31 UTC, cpl121 requested changes

2024-03-13 09:31 UTC, cpl121 commented on packages/shared/locales/en.json
> +                    "version": "Version"
There are more references to clean in this file like `views.settings.localProofOfWork` or `general.transferPow`

2024-03-19 08:30 UTC, cpl121 approved these changes

2024-03-19 09:46 UTC, begonaalvarezd approved these changes

2024-03-19 09:46 UTC, merged