feat: split the accounts from the list into two WIP
iotaledger/firefly pull request #8186
Opened 2024-03-11 10:53 UTC by cpl121

Closes #8179 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-03-15 15:32 UTC, marc2332 requested changes
maybe try reducing the margin on top of "Pending accounts"
![image](https://github.com/iotaledger/firefly/assets/38158676/d00abc69-879f-4636-b174-33c068308334)

Also, it seems like I cannot scroll in the pending accounts section

![image](https://github.com/iotaledger/firefly/assets/38158676/46944fbc-d5d1-4fa8-a98c-5a63b178d4c9)

2024-03-18 16:30 UTC, evavirseda requested changes
:pray:

2024-03-18 16:30 UTC, evavirseda commented on packages/desktop/components/AccountManagementList.svelte
> +        <left-pane-container class="flex flex-col space-y-4 h-full scrollable-y">
this should be fixed, it's cut off :police_car: 
![image](https://github.com/iotaledger/firefly/assets/72078237/c2a03533-c115-4f8f-b3a5-71b685b501f7)

suggestion--> `<list-wrapper class="flex flex-col space-y-2 px-2">`

2024-03-19 08:55 UTC, evavirseda approved these changes
nice job :rocket:

2024-03-19 09:50 UTC, begonaalvarezd approved these changes

2024-03-19 09:50 UTC, merged