fix: crash-accounts-if-not-selected-output
iotaledger/firefly pull request #8204
Opened 2024-03-15 10:12 UTC by cpl121

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-03-15 10:15 UTC, marc2332 requested changes

2024-03-15 10:15 UTC, marc2332 commented on packages/desktop/views/dashboard/account-management/AccountManagement.svelte
> +        {/if}
else add a message in an `else` so the view isn't empty

2024-03-15 10:41 UTC, marc2332 requested changes

2024-03-15 10:41 UTC, marc2332 commented on packages/shared/locales/en.json
>              "title": "Delegation",
```suggestion
            "emptyAccounts": "There is no account to show, activate one first."
        },
        "delegation": {
            "title": "Delegation",
```

2024-03-15 10:42 UTC, marc2332 commented on packages/shared/locales/en.json
>              "title": "Delegation",
the rest LGTM

2024-03-15 14:18 UTC, marc2332 approved these changes

2024-03-18 14:41 UTC, evavirseda requested changes

2024-03-18 14:41 UTC, evavirseda commented on packages/shared/locales/en.json
> +            "emptyAccounts": "There is no account to show, activate one first."
```suggestion
            "emptyAccounts": "There are no accounts to show, activate one first."
```

2024-03-19 09:42 UTC, begonaalvarezd approved these changes

2024-03-19 09:42 UTC, merged