feat: update network interfaces WIP
iotaledger/firefly pull request #8210
Opened 2024-03-15 16:57 UTC by cpl121

Closes #8209 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-03-19 08:39 UTC, marc2332 requested changes

2024-03-19 08:39 UTC, marc2332 commented on packages/desktop/components/popups/NodeInfoPopup.svelte
> +    import { INodeInfo, NetworkMetricsResponse } from '@iota/sdk/out/types'
Shouldn't `INodeInfo` now be `INodeInfoResponse`?

2024-03-20 09:32 UTC, evavirseda approved these changes
looks good :+1:

2024-03-21 11:38 UTC, begonaalvarezd approved these changes
🔥

2024-03-21 11:39 UTC, merged