feat: show total tokens in the asset list
iotaledger/firefly pull request #8249
Opened 2024-03-22 10:50 UTC by evavirseda

## Summary

> Closes #8006 
...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-03-25 16:34 UTC, cpl121 requested changes

2024-03-25 16:34 UTC, cpl121 commented on packages/desktop/components/popups/TokenInformationPopup.svelte
> +                        subBreakdown={balanceSummary?.details}
bad format when calculating base unit token
![Captura de pantalla de 2024-03-25 17-31-40](https://github.com/iotaledger/firefly/assets/100352899/270cbf54-5a6f-4bdf-bd11-ebd783ebdc9f)

2024-03-25 16:34 UTC, cpl121 commented on packages/shared/components/tiles/AssetTile.svelte
> +    $: total = (asset?.id === MANA_ID ? asset?.balance?.available : asset?.balance?.total) ?? 0
I don't understand this line 🥲

2024-03-26 19:27 UTC, cpl121 approved these changes
🚀

2024-03-27 11:26 UTC, marc2332 requested changes

2024-03-27 11:26 UTC, marc2332 commented on packages/shared/components/BalanceSummarySection.svelte
> +    function handleAmount(isBaseToken: boolean = false, amount: number) {
This should be receiving `asset` as function parameter, just like `isBaseToken` and `amount`

2024-03-27 11:26 UTC, marc2332 commented on packages/shared/components/BalanceSummarySection.svelte
> +        if (!asset) {
same

2024-03-27 11:26 UTC, marc2332 commented on packages/shared/components/BalanceSummarySection.svelte
> +    function handleCurrencyAmount(isBaseToken: boolean = false, amount: number) {
same

2024-03-27 11:26 UTC, marc2332 commented on packages/shared/components/BalanceSummarySection.svelte
> +        if (!asset) {
same, and you might as well add `baseCoin`

2024-03-27 12:49 UTC, begonaalvarezd requested changes
- base token is being displayed with mana
![image](https://github.com/iotaledger/firefly/assets/3624944/04750ab1-8774-4b32-9f24-49d9ae3bae47)
- remove the secondary value if the asset has no fiat value
- in token details popup, simplify the breakdown to be:
    - Total Balance                                amount
          - Available                                 amount
          - Conditionally Locked              amount

2024-03-27 14:57 UTC, marc2332 commented on packages/shared/components/BalanceSummarySection.svelte
> +        if (!asset) {
Now that I think about this one, I don't think it was worth adding, but it's fine

2024-03-27 14:57 UTC, marc2332 approved these changes

2024-03-28 16:26 UTC, begonaalvarezd approved these changes

2024-03-28 16:26 UTC, merged