fix: Fix async claim error
iotaledger/firefly pull request #8315
Opened 2024-04-04 16:30 UTC by marc2332

Depends on https://github.com/iotaledger/firefly/pull/8306
Closes https://github.com/iotaledger/firefly/issues/8309

I am not sure if this is a perfect solution, suggestions are welcome.

2024-04-04 17:20 UTC, cpl121 requested changes

2024-04-04 17:20 UTC, cpl121 commented on packages/shared/lib/core/wallet/actions/setOutgoingAsyncActivitiesToClaimed.ts
> +                    }
```suggestion
            let walletOutput = await wallet.getOutput(activity.outputId)
            let outputMetadata: OutputMetadataResponse
            if (walletOutput) {
                outputMetadata = walletOutput.metadata
            } else {
                walletOutput = await client.getOutput(activity.outputId)
                outputMetadata = await client.getOutputMetadata(activity.outputId)
            }
            const nodeProtocolParameters = get(nodeInfoProtocolParameters)
            if (nodeProtocolParameters && walletOutput.metadata.spent) {
                const claimedDate = new Date(
                    getUnixTimestampFromNodeInfoAndSlotIndex(
                        nodeProtocolParameters,
                        walletOutput.metadata.spent.slot
                    )
                )
                const isClaimed =
                    walletOutput.metadata &&
                    isOutputClaimed(walletOutput.output as BasicOutput, walletOutput.metadata, claimedDate)
                if (isClaimed && claimedDate) {
                    updateAsyncDataByActivityId(wallet.id, activity.id, {
                        asyncStatus: ActivityAsyncStatus.Claimed,
                        claimedDate,
                    })
                }
            }
```

2024-04-04 21:08 UTC, cpl121 approved these changes

2024-04-05 11:37 UTC, evavirseda approved these changes

2024-04-05 11:39 UTC, merged