feat: create delegation activity
iotaledger/firefly pull request #8366
Opened 2024-04-10 13:14 UTC by evavirseda

## Summary

> Closes #8335 

...

## Changelog

```
- Please write a list of changes
```

## Testing

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

2024-04-11 07:12 UTC, marc2332 requested changes

2024-04-11 07:12 UTC, marc2332 commented on packages/shared/locales/en.json
> +                "Confirmed": "delegation created",
Feel free to update `account.creation` as well if you wish to
```suggestion
                "Pending": "Creating delegation",
                "Confirmed": "Delegation created",
```

2024-04-11 07:12 UTC, marc2332 commented on packages/shared/lib/core/wallet/utils/generateActivity/generateActivities.ts
> +    }
I think this should be something like

```ts
const containsDelegationActivity = outputs.some((output) => output.output.type === OutputType.Delegation)
if (containsDelegationActivity) {
    const delegationActivities = await generateActivitiesFromDelegationOutputs(processedTransaction, wallet)
    activities.push(...delegationActivities)
}

if (
    (!containsFoundryActivity && !containsNftActivity && !containsAccountActivity && !governanceOutput && !containsDelegationActivity) ||
    isSentToImplicitAccountCreationAddress
) {
    const basicActivities = await generateActivitiesFromBasicOutputs(processedTransaction, wallet)
    activities.push(...basicActivities)
}

```

2024-04-11 07:12 UTC, marc2332 commented on packages/shared/components/DelegationActivityDetails.svelte
> +    $: amount = Number(activity?.delegatedAmount)
What's the point of storing the `delegatedAmount` as a string if we are going to convert it into a Number later on. We could just convert it into a number when the activity is generated.

2024-04-11 07:12 UTC, marc2332 commented on packages/shared/components/DelegationActivityDetails.svelte
> +    $: amount = Number(activity?.delegatedAmount)
```suggestion
    $: amount = activity.delegatedAmount
```

2024-04-11 07:12 UTC, marc2332 commented on packages/shared/components/DelegationActivityDetails.svelte
> +    $: amount = Number(activity?.delegatedAmount)
I also think that `AmountBox` should accept a bigint instead of a number but that's not an issue of this PR

2024-04-11 07:12 UTC, marc2332 commented on packages/shared/lib/core/wallet/utils/generateActivity/generateSingleDelegationActivity.ts
> +    const delegatedAmount = output.delegatedAmount.toString()
```suggestion
    const delegatedAmount = Number(output.delegatedAmount)
```

2024-04-11 09:46 UTC, marc2332 requested changes

2024-04-11 09:46 UTC, marc2332 commented on packages/shared/components/DelegationActivityDetails.svelte
> +    $: amount = activity?.delegatedAmount
```suggestion
    $: amount = activity.delegatedAmount
```

2024-04-11 11:09 UTC, cpl121 requested changes
we could add a tab like in account
![Captura de pantalla de 2024-04-11 12-13-59](https://github.com/iotaledger/firefly/assets/100352899/9310e859-7062-4fb6-a16d-6eab43a7ef6c)

Adding in the delegation tab
- ValidatorAddress
- DelegatedAmount
- DelegationId (?)
- StartEpoch (?)
wdyt?

2024-04-11 11:09 UTC, cpl121 commented on packages/shared/components/tiles/tileContents/DelegationActivityTileContent.svelte
> +        text: truncateString(activity.validatorAddress, 6, 6),
I think it is better to use the account address of the one that created the delegation, as is the case with the rest of the activities

2024-04-12 08:50 UTC, cpl121 requested changes
much prettier 👏🏼 
![Captura de pantalla de 2024-04-12 10-39-16](https://github.com/iotaledger/firefly/assets/100352899/e8cf06d7-9742-4e0f-afa6-14a9f579b73d)

last comment 🙏🏼

2024-04-12 08:50 UTC, cpl121 commented on packages/shared/lib/core/wallet/utils/generateActivity/generateSingleDelegationActivity.ts
> +    const giftedStorageDeposit = 0
```suggestion
   const { storageDeposit, giftedStorageDeposit } = await getStorageDepositFromOutput(output)
```

2024-04-12 08:56 UTC, cpl121 approved these changes

2024-04-16 10:35 UTC, marc2332 approved these changes

2024-04-16 15:52 UTC, merged